tsuru/tsuru

- .travis.yml
Because it might not always be stable.
See https://github.com/travis-ci/travis-ci/issues/2944:
> It's probably best to keep tip as an allowed_failures entry if you're
> concerned about this causing disruptions.
> .travis.yml: Allow go tip to fail

- cmd/tsr/token.go
Make sure output ends with a newline, as this is a UNIX convention to always have a newline at the end of text.
> Make `tsr token` include newline

- api/app.go
- api/app_test.go
- api/auth.go
- api/auth_test.go
- api/plan.go
- api/plan_test.go
for a bunch of endpoints that output JSON.
This makes output nicer when accessing via a tool, such as HTTPie
> Set Content-Type: application/json

- .travis.yml
Hoping that this might help Travis CI tests to pass even when there are sporadic failures relating to MongoDB (e.g.: #1048, #1049)
> .travis.yml: Use travis_retry for `make test`

- .travis.yml
Add `free` and `top -b -n 1 -o RES | head -n 15` so we can try to see where all of the memory is going.
Refs: #1045
> .travis.yml: ++memory info in after_failure

- .travis.yml
to save some memory and maybe lessen chance of OOMs on Travis
(although I think MongoDB is using a lot more memory than these two are).
> .travis.yml: Stop postgresql and mysql

- etc/tsuru-docker-template.conf
- etc/tsuru.conf
admin-listen (port 8888) is not used anymore in tsuru, according to @andrewsmedina
> Remove "admin-listen" stuff from configs

- docs/using/go.rst
- docs/using/logging.rst
because I found evidence of the old admin-listen which was on port 8888
and now when I grep for 'admin-listen|:8888', I get false positives from
the docs.
> Change sample port in docs from 8888 to 8100

- auth/native/data.go
- cmd/auth.go
- cmd/auth_test.go
Mostly using "reset" in place of "redefine", which looks better to this
native English speaker's eyes. Also "successfully" was misspelled before
with only one "l".
> Tweak password reset messages

- auth/scheme.go
- auth/scheme_test.go
Slightly clearer since "scheme" to a lot of people implies a URL.
> "Unknown scheme" => "Unknown auth scheme"

- docs/using/tsuru.yaml.rst
- provision/docker/healthcheck.go
- provision/docker/healthcheck_test.go
This PR introduce an `allowed_failures` parameter for applications' healthcheck. This is the number of allowed failures before that the health check consider the application as unhealthy (the default value is for sure 0)
This is especially interesting when sometimes there's some need of asynchronous process to be started before the application can have its normal behavior.
> Allow healthcheck failures

- api/server.go
- provision/docker/provisioner.go
- provision/provision.go
This is my stab at making tsuru display the list of nodes in the Docker cluster when tsuru starts up.
It seems useful to know what your Docker nodes are, especially since I've seen at least a few times on gitter/IRC, people were puzzled when they got an error about having a node in the config file that was already registered.
```
vagrant@vagrant-ubuntu-trusty-64:~/go/src/github.com/tsuru/tsuru$ rm -rf build; make run-tsr-api
godep go build -o build/tsr cmd/tsr/*.go
build/tsr api
Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
Using mongodb database "tsurudb" from the server "127.0.0.1:27017".
Using "docker" provisioner.
nodeList = [{http://127.0.0.1:2375 {0001-01-01 00:00:00 +0000 UTC false} map[LastSuccess:2015-01-04T18:22:22Z pool:theonepool]}] …
```
> Show Docker nodes at startup

- api/server.go
- router/galeb/router.go
- router/hipache/router.go
- router/router.go
Example output:
[marca@marca-mac2 tsuru]$ make run-tsr-api
build/tsr api
Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
Using mongodb database "tsurudb" from the server "127.0.0.1:27017".
Using hipache router "10.128.40.70.xip.io".  <--------------------- This is the new information
Using "docker" provisioner.
Using "native" auth scheme.
tsuru HTTP server listening at 0.0.0.0:8080...
Mainly I am hoping that this helps people to understand the various pieces of tsuru better and what depends on what, because this is what I struggled with the most when I first started playing with it.
> Display info about router on startup

- cmd/client.go
Prevents stuff running together when using verbose mode. E.g.:
$ tsuru-admin -v 2 user-create ${EMAIL}
Password: ******
Confirm: ******
*************************** <Request uri="/users"> **********************************
POST /users HTTP/1.1
Host: 127.0.0.1:8080
Connection: close
Authorization: bearer d2f838d903e100b56beab35d76718924065d7a36
{"email":"me@mycompany.com", "password":"secret"}*************************** </Request uri="/users"> **********************************
*************************** <Response uri="/users"> **********************************
HTTP/1.1 500 Internal Server Error
...
> Make user-create request end with newline

- cmd/cmd.go
- cmd/cmd_test.go
This is an alternative (and sort of opposite to) https://github.com/tsuru/tsuru/pull/1069
Instead of displaying commands in columns to cram more in the space, this uses the space to display a bit of info about each command, and is probably more typical of command-line tools, as this is seen in git, hg, pip, go, etc.
```
$ tsuru
tsuru version 0.14.0.
Usage: tsuru command [args]
Available commands:
app-create           Create a new app
app-deploy           Deploys set of files and/or directories to tsuru server
app-grant            Grants access to an app to a team
app-info             Show information about your app
app-list             List all your apps
app-log              Show logs for an app
app-remove           Removes an app
app-restart          Restarts an app
app-revoke …
```
> List commands with short description

- cmd/cmd.go
- cmd/cmd_test.go
because a lot of other Linux commands support these (E.g.: `git`), so why not?
This is much friendlier than the current behavior:
```
$ tsuru --help
Error: command "--help" does not exist
$ tsuru --version
Error: command "--version" does not exist
```
> Make --help and --version work

- docs/installing/api.rst
The documentation is wrong since the last release, this PR updates it.
> Change `tsuru-admin` commands by `tsuru` after installation

- cmd/cmd.go
- cmd/cmd_test.go
What do you think of, instead of just the prefix, consider any occurrence of the argument in the command name when deciding to suggest the command or not. Here is a brief example:
* Before this change:
```
► tsuru log
tsuru: "log" is not a tsuru command. See "tsuru help".
Did you mean?
login
logout
```
* After this change:
```
► tsuru log
tsuru: "log" is not a tsuru command. See "tsuru help".
Did you mean?
app-log
login
logout
```
As far as I could test, [tsuru/tsuru-client](http://github.com/tsuru/tsuru-client) wasn't affected by this change. Please advise me if any other project is, though.
> cmd: increase the chance of a command being suggested

- docs/installing/gandalf.rst
There are three steps not two.
> Correct small typo in Gandalf set-up documentation

- cmd/client.go
- cmd/client_test.go
- cmd/cmdtest/transport.go
When the API is behind an AWS ELB and all instances are unhealthy, the ELB
will respond to client requests with a 503 status code and reason but no body
text. As demonstrated by:
➜  ~  curl -v http://tsuru.redacted:8080/info
* Hostname was NOT found in DNS cache
*   Trying xx.xx.xx.xx...
* Connected to tsuru.redacted (xx.xx.xx.xx) port 8080 (#0)
> GET /info HTTP/1.1
> User-Agent: curl/7.37.1
> Host: tsuru.redacted:8080
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host tsuru.redacted left intact
This lack of body causes tsuru-client not to print any error message to
indicate what has gone wrong. Instead you get:
➜  ~  tsuru app-list
Error:
Make this clearer by using …
> cmd: Error with HTTP status when body is empty

- api/app_test.go
`TestSwapApp1Locked` has been intermittently failing for me. I can't
reproduce it when running the test by itself, but can when run in
conjunction with `TestSwap`:
➜  tsuru git:(master) go test github.com/tsuru/tsuru/api -check.f TestSwap -check.v
PASS: app_test.go:2853: S.TestSwap      0.486s
----------------------------------------------------------------------
FAIL: app_test.go:2877: S.TestSwapApp1Locked
app_test.go:2895:
c.Assert(err, check.ErrorMatches, "app1: App locked by x, running /test. Acquired in .*")
... value = nil
... regex string = "app1: App locked by x, running /test. Acquired in .*"
... Error value is nil
----------------------------------------------------------------------
PASS: app_test.go:2898: S.TestSwapApp2Locked    10.097s
PASS: app_test.go:2962: …
> api: Fix intermittent SwapApp test failure

- router/hipache/router.go
- router/hipache/router_test.go
This error occurs when you try to use the suffix domain like cname.domain.com to create cname.domain.com.br
another example:
cname.domain.com
cnamenew.domain.com
> Fix when adding cname using the suffix domain

- docs/reference/config.rst
RsT doesn't support code formatting inside hyperlinks:
http://docutils.sourceforge.net/FAQ.html#is-nested-inline-markup-possible
Fix the rendering by making the link a separate reference. Keeping the
formatting means that it's easy to see the possible values.
To match the other routers.
> docs/reference/config: Fix router links

- docs/roadmap.rst
Looks like a copy/paste error from the preceding line.
> docs/roadmap: Fix link to dockerize install

- docs/reference/api.rst
This is good. We should tell people about it.
The trailing slash is intentional per `api/server.go`.
> docs/reference/api: Document /healthcheck endpoint

- .travis.yml
- Godeps/Godeps.json
- router/vulcand/router_test.go
Now that the fix for `UpsertServer()` has been merged and we've bumped our
dependency. This makes running the tests easier, because you don't need to
have etcd installed and we don't need to cleanup the datastore before each
test.
> router/vulcand: Test against memng instead of etcd

- router/vulcand/router.go
- router/vulcand/router_test.go
Which ensures that it gets a successful response from the vulcand API.
> router/vulcand: Add healthcheck

- api/platform.go
Installing a platform can take a long time and we
had issues with platform-add/update timing out
after 60 seconds (default Nginx proxy timeout).
We have implemented a simple workaround similar how
deployment endpoint works - using a keep alive writer
and a 30s "please wait" heartbeat.
See also this issue for more thoughts: https://github.com/tsuru/tsuru/issues/1239
> Platform Add / Update Heartbeat

- api/auth.go
When querying the user database, if a user is not found the api currently
returns a server error (5XX) which is inconsistent with the other api
calls. This commit updates this behaviour.
I couldn't see any test implications but am happy to update if this is the case.
[#1242]
> Changed the return code on delete a user to 404 if not found

- Makefile
When you miss a tsuru dependency, it shows an invalid URL for the documentation.
> Fix URL for documentation in Makefile

- docs/using/java.rst
Adding docs to environment variable JAVA_MAX_MEMORY (it's equal -Xmx).
Refs: https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html#wp999528
> Change docs to add set memory in java apps

- provision/docker/bs/cmd.go
Quick fix to validate user input for setting env variables.
For instance executing: 
* ```tsuru-admin bs-env-set BS_DEBUG```
* ```tsuru-admin bs-env-set =true```
* ```tsuru-admin bs-env-set =```
results in panic.
```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/tsuru/tsuru/provision/docker/bs.(*EnvSetCmd).Run(0xc8200db3e0, 0xc8200971d0, 0xc820097220, 0x0, 0x0)
/private/tmp/tsuru-admin20151027-27582-1peo0xl/src/github.com/tsuru/tsuru/provision/docker/bs/cmd.go:41 +0x8ed
github.com/tsuru/tsuru/cmd.(*Manager).Run(0xc820102480, 0xc820107740, 0x1, 0x1)
/private/tmp/tsuru-admin20151027-27582-1peo0xl/src/github.com/tsuru/tsuru/cmd/cmd.go:192 +0x18ca
main.main()
/private/tmp/tsuru-admin20151027-27582-1peo0xl/src/github.com/tsuru/tsuru-admin/main.go:70 +0xba
goroutine …
```
> provision/docker/bs: fix panic index auth of range

- api/app.go
- api/app_test.go
- api/permission.go
- app/app.go
- app/app_test.go
- app/deploy.go
- provision/docker/image.go
- provision/docker/provisioner.go
- provision/docker/provisioner_test.go
- provision/docker/repository.go
- provision/docker/repository_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- provision/provisiontest/fake_provisioner_test.go
- repository/gandalf/gandalf.go
Adds support to filter app list by unit status. You can pass more than one status, separated by `,`:
```
curl -H 'Authorization: b token'  "http://localhost:8080/apps?status=stopped,asleep"
```
> App list filter by status

- iaas/ec2/iaas.go
- iaas/ec2/iaas_test.go
There's a lot of ugly magic going on, specially when we need to load a
slice of pointers (like in []*ec2.BlockDeviceMapping). We have the
option to explicitly handle each field, but then it's not extensible.
Anyway, feedback is very welcome!
I choose to handle monitoring explicitly because I think that it doesn't
make sense to force tsuru users to provide monitoring='{"Enabled":true}'
when they can simply provide monitoring-enabled=true.
> iaas/ec2: support all fields in ec2.RunInstancesInput

- api/plan.go
- api/plan_test.go
This is related to #1394.
With this change, It should be possible to user to use the following notation in order to create a plan:
`$ tsuru-admin plan-create basics -c 2 -m 1G -s 1G -r hipache -d`
The following options are available:
- K for kilobytes
- M for megabytes
- G for gigabytes
This is my first PR for a Golang project, so I'm not so sure about where the function `getSize ` should be placed, but some feedback is welcome :)
> Supports for '512M' as value for memory and swap

- docs/installing/api.rst
This fixes:
```
flag provided but not defined: --config
Usage of tsuru flags:
-h, --help  (= false)
Display help and exit
-v, --verbosity  (= 0)
Verbosity level: 1 => print HTTP requests; 2 => print HTTP requests/responses
--version  (= false)
Print version and exit
```
> [docs] Fix root-user-create call

- api/platform.go
- api/platform_test.go
Make update on platform behaves like delete when resource is not found
> Update returns a 404 when platform is not found

- provision/docker/container/container.go
- provision/docker/container/container_test.go
Unset memory limits for builder container and give it a highest score possible on a container OOM kill event.
> provision/docker: unset memory limits for builder container

- api/deploy_test.go
- app/deploy.go
- app/deploy_test.go
Tsuru accepts any value as a parameter to app-deploy-rollback, and you won't believe what happens next:
```
% tsuru app-deploy-rollback app-deploy-rollback --app test-chico
Are you sure you want to rollback app "test-chico" to image "app-deploy-rollback"? (y/n) y
---- Starting 0 new units  ----
---- Binding and checking 0 new units ----
---- Setting router healthcheck (Path: /) ----
---- Removing routes from old units ----
---> Removed route from unit b7df34b7b8 [web]
---- Removing 1 old unit ----
---> Removed old unit b7df34b7b8 [web]
---- Unbinding 1 old unit ----
---> Removed bind for old unit b7df34b7b8 [web]
% tsuru app-deploy-list -a test-chico
+-------------------------+----------+--------+-------------------------+-------+
| Image (Rollback)        | Origin   | User   | Date …
```
> app/deploy: reject images that are not valid for rollback

- api/deploy.go
- api/deploy_test.go
- app/deploy.go
- app/deploy_test.go
This PR includes two fixes to #1454:
1. When displaying deployment information, set origin to "git" whenever origin is not defined and commit is defined
1. When saving a new deployment, set origin to "git" whenever origin is not defined and commit is defined, like tsuru used to do before the release of 1.1
The first fix can be replaced with a migration that make all deployments compatible with the logic implemented by the second fix. I wanted to open the pull request and let anyone jump in with thoughts/suggestions.
Fix #1454.
> Properly save and display origin for git-based deployments

- api/app.go
- api/app_test.go
- app/app.go
- app/app_test.go
- provision/docker/provisioner.go
- provision/docker/provisioner_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- provision/provisiontest/fake_provisioner_test.go
This PR solves the issue #855 implementing the flag --isolated to app-run command.
If accepted user will can execute command in an ephemeral container.
> Implements isolated flag to app-run command

- auth/native/data.go
- auth/native/data_test.go
- auth/native/native_test.go
- auth/native/testdata/email-reset-password.txt
- auth/native/testdata/email-reset-success.txt
- auth/native/user.go
- docs/reference/config.rst
Hi @andrewsmedina, 
Could you please review this pull request.
Should I update the Tsuru **documentation**?
Now, we have two more configurations: 
1. `email-reset-password-template-file`: path/to/file/template.txt
2. `email-reset-password-successfully-template-file`: path/to/file/template.txt
Issue: #1164
> Allow the customization of the email template for reset-password message

- README.md
Github repository is the place where devs want to take a look at the code and quick test the project.
With this quickstart section at README new users can get a first good impression and fast test tsuru without need to get into documentation
> add quickstart section for README.md

- api/app.go
- api/app_test.go
I also "reverted" d4a85c9b857841bfd4a80595cf109daee48af307 because
there's no need to use the getter methods here.
Closes #1529.
> api: include pool name on /apps response

- healer/healer_node.go
- healer/healer_node_test.go
Keeping this data might lead to misbehavior on the healer when the
underlying IaaS reuses an IP.
An actual healing I faced right after launching a node (like 1 min
after):
```
lastcheck:
checks:
- err: ''
name: writableRoot
successful: true
- err: ''
name: createContainer
successful: true
time: '2017-04-17T19:52:14.151000'
node:
_id: https://1.2.3.4:2376
metadata:
amazonec2-iam-instance-profile: docker-nodes
amazonec2-instance-type: m3.medium
amazonec2-private-address-only: 'true'
amazonec2-root-size: '60'
amazonec2-security-group: docker-nodes
amazonec2-subnet-id: subnet-0123456
amazonec2-tags: Name,docker-node
amazonec2-vpc-id: vpc-0123456
driver: amazonec2
iaas: dockermachine
iaas-id: mypool-3ccdcb8302c6960f54a521680d44ca94
insecure-registry: registry.example.com:5000
memory: …
```
> healer: remove node status after healing a node

- cmd/cmd.go
- cmd/cmd_test.go
- cmd/topics.go
Creating a pull-request for discussion related to #1527.
With these changes, the first part of any dash separated command will create an implicit topic on tsuru. Which we can review and add proper descriptions latter.
Building tsuru-client with these changes result in the following behavior:
```
$ tsuru help
tsuru version 1.2.0-dev.
Usage: tsuru command [args]
Available commands:
app-create                   Creates a new app using the given name and platform
... ALL STILL COMMANDS LISTED .. 
Use tsuru help <commandname> to get more information about a command.
Available topics:
app                  
bs                   
certificate          
cname                
containers           
docker               
env                  
event                
install              
key …
```
> cmd: implicit topics help and allow space as separator

- api/auth.go
- api/auth_test.go
Fixes bug on Issue #1430 where in a situation that a user has only basic permissions and is not assigned to any teams, using `tsuru user-list` command would not show anything other than the headers.
> User-list bug fix

- provision/kubernetes/node.go
- provision/kubernetes/node_test.go
- provision/kubernetes/provisioner_test.go
Adds the cluster name as metadata in Kubernetes nodes. Fixes #1593
> Kubernetes node cluster metadata

- api/node.go
- permission/permitems.go
- permission/permlist.go
This PR disables the need for `PermMachineCreate` and `PermMachineDelete` from adding and removing nodes. `PermMachineCreate` was removed since it wasn't used anywhere.
> api/node: disables the need for machine perms

- builder/builder.go
- builder/builder_test.go
- builder/docker/platform.go
- builder/docker/platform_test.go
When building platforms, instead of trying to build it for every available builder, now it stops after the first successful build.
Eventually, when we start supporting other types of containers, we will need to change this behavior.
> Fix platform builder

- db/storage.go
It was deprecated in MongoDB 3.2
> db: remove forceIdIndex from capped collection creation

- api/app.go
- api/app_test.go
- app/actions.go
- app/actions_test.go
- app/app.go
- app/app_test.go
- app/bind/binder.go
- app/migrate/migrate.go
- app/migrate/migrate_test.go
- cmd/tsurud/migrate.go
- provision/kubernetes/deploy_test.go
- provision/provisiontest/fake_provisioner.go
- provision/provisiontest/fake_provisioner_test.go
- service/actions.go
- service/actions_test.go
- service/bind_test.go
- service/service_instance_test.go
Currently, after binding two service-instances with the same name (but different services) to a single app may cause tsuru to remove environment variables injected by both instances when unbinding either service-instance.
This PR also improves existing test cases and add new ones to ensure this bug is reproducible and gone for good.
> fix service unbind causing wrong env vars to be removed from app

- api/app_test.go
- api/context/context.go
- api/context/context_test.go
- api/shutdown/shutdown_test.go
- api/suite_test.go
This PR replaces the use of gorilla/context in the api/context pkg with the std library context (introduced in go 1.7).
Fixes #1503
> api/context: replaces gorilla/context with stdlib context

- volume/volume.go
- volume/volume_test.go
With this we validate the volume name as other names (team, pool, etc). Also adds some test cases.
> volume: validates volume name

- api/app.go
- api/app_test.go
This prevents the value of a private variable from being shown on event info.
> api: hides private env value from event data

- api/app_test.go
- api/server.go
- api/service_instance_test.go
- app/app.go
- provision/docker/suite_test.go
- provision/swarm/provisioner_test.go
- provision/swarm/suite_test.go
- service/actions_test.go
- service/bind_test.go
- service/service_instance.go
- service/service_instance_test.go
- service/sync.go
- service/sync_test.go
This PR adds a goroutine that syncs every application service binds every each given interval. This is required for provisioners which we are not aware when a unit is rescheduled, such as kubernetes or swarm. This will also remove the dependency on the service API since the bind/unbind operation will be able to fail when the unit is rescheduled and will by retried by the syncer.
> Service Bind sync

- app/log.go
- db/dbtest/db.go
- db/storage/storage.go
Also, this reverts "app: reuse connection to log database.
This commit caused mongodb connections to leak and collections to get
locked indefinitely.
> db: do not call create repeatedly on the same collection

- app/app.go
- app/app_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/swarm/provisioner.go
- provision/swarm/provisioner_test.go
- provision/swarm/suite_test.go
- service/actions.go
- service/endpoint.go
- service/service_instance.go
This PR moves the call to app.Bind from the provisioners to the app.RegisterUnit method.
This also changes ServiceInstance.BindUnit to **not** return an error when the unit is already bound to the service.
> Moves app.Bind to app.RegisterUnit

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/swarm/docker.go
This PR makes swarm and kubernetes ignore the result of the curl for registering the unit with the tsuru api.
> provision/swarm,kubernetes: ignores errors when registering units

- service/sync.go
- service/sync_test.go
This PR makes sure that BindSyncer only creates events when it actually changes one of the Binds on an app.
> service: prevents BindSyncer from flooding events

- event/block.go
- event/block_test.go
- event/event.go
- event/event_test.go
This PR adds some metrics to the events package. Added metrics are:
1. tsuru_events_current - tracking the number of events running by kind
2. tsuru_events_duration_seconds - tracks the duration of each event. Defining the buckets for the histogram is kinda tricky since the expected duration of each kind of event is highly variable.
3. tsuru_events_rejected - tracks the events that failed to be created, there are specific "reasons" for blocked events, locked events and throttled events.
This is how they look on `/metrics`:
```
tsuru_events_current{kind="app.deploy"} 0
tsuru_events_current{kind="bindsyncer"} 0
tsuru_events_current{kind="event-block.add"} 0
tsuru_events_current{kind="event-block.remove"} 0
tsuru_events_duration_seconds_bucket{kind="app.deploy",le="1"} 4 …
```
> event: adds basic instrumentation

- net/client.go
- provision/docker/healthcheck.go
This PR creates a new client to our net package that does not follow any redirects and uses this client for `provision/docker` healthchecks.
> net,provision/docker: disable following redirects on healthchecks

- api/autoscale_test.go
- autoscale/autoscale.go
- autoscale/autoscale_test.go
- autoscale/rule.go
- docs/advanced_topics/node_scaling.rst
- docs/reference/config.rst
- provision/docker/scheduler.go
- provision/docker/scheduler_test.go
This PR removes the need to enable the autoscale using the configuration file and only relies on the rules registered for each pool.
This also makes sure we skip provisioners with error instead of checking other provisioners nodes.
Fixes #1456.
> autoscale: always enabled and skipping provisioners with error

- api/middleware.go
- api/middleware_test.go
- cmd/client.go
- cmd/client_test.go
This PR adds a header to control how verbose errors are sent to clients, i.e if they include a stack trace. This header is set using the `--verbosity` flag on our client.
Fixes #1647
> api: uses header to decide error verbosity

- api/nodecontainer_test.go
- provision/nodecontainer/nodecontainer.go
- provision/nodecontainer/nodecontainer_test.go
- scopedconfig/scopedconfig.go
- scopedconfig/scopedconfig_test.go
One use case of this is disabling a cadvisor node-container on
kubernetes pools as it's already bundled inside kubelet.
> all: allow disabling node container on selected pools

- event/event.go
- event/event_test.go
Currently if we try to cancel the same event twice, the TryCancel message will output that the event requested does not exist. This handles this case better.
> event: outputs better error message for repeated cancelations

- api/service_instance_test.go
- service/service_instance.go
- service/service_instance_test.go
When the service instance team owner is updated, adds it to the teams array.
Also, makes the update operation safer, allowing only a subset of allowed fields to be updated.
> Fix service instance update

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This serves both as a workaround to kubernetes/kubernetes#51142 and to help
prevent kubernetes' GC from removing the main container while we're running
docker commit on it. This latter issue should be fixed once moby/moby#30696
is in.
> provision/kubernetes: ugly hack for deploy containers to wait each other

- builder/docker/container.go
- provision/docker/container/container.go
- provision/docker/container/container_test.go
- provision/dockercommon/docker.go
- provision/swarm/docker.go
This ensures we always have the output log from the deploy.
> all: use json-file log driver for deploy containers

- app/migrate/migrate.go
- app/migrate/migrate_test.go
This makes this migration non-destructive making rolling back to a
previous tsuru version easier.
> app/migrate: do not delete TSURU_SERVICES env var during migration

- provision/swarm/provisioner.go
- provision/swarm/provisioner_test.go
This could cause tsuru to return 404 errors on /node/status requests if the
first queried provisioner was swarm and no swarm clusters existed.
> provision/swarm: return node not found err if no cluster found

- api/service_instance.go
- api/service_instance_test.go
- docs/services/api.rst
- docs/services/build.rst
- permission/permitems.go
- permission/permlist.go
- service/endpoint.go
- service/endpoint_test.go
Add a `plan` parameter to service instance update route. As this field isn't persisted in the DB, it's only for notifying the change to the service API
> Service instance update plan

- cmd/render.go
- cmd/render_test.go
```
name      old time/op    new time/op    delta 
String-4    18.5ms ± 4%    1.5ms ±16%  -92.07%  (p=0.004 n=5+6)
name      old alloc/op   new alloc/op   delta 
String-4    60.2MB ± 0%    0.5MB ± 0%  -99.18%  (p=0.004 n=5+6)
name      old allocs/op  new allocs/op  delta 
String-4     34.9k ± 0%    15.5k ± 0%  -55.67%  (p=0.002 n=6+6)
```
> cmd: improve performance of table rendering

- app/quota_test.go
- auth/quota_test.go
- event/event_test.go
- healer/healer_node_test.go
- iaas/iaas_test.go
- provision/docker/provisioner_test.go
- provision/docker/scheduler_test.go
- provision/limiter_test.go
- provision/nodecontainer/bs_test.go
- router/routertest/race_test.go
- safe/counter_test.go
- scopedconfig/scopedconfig_test.go
- service/service_instance_test.go
- tsurutest/recorder_test.go
A small change in how we set `runtime.GOMAXPROCS` in tests, to make the code clearer.
> Refactor runtime.GOMAXPROCS calls

- Gopkg.lock
- provision/docker/actions.go
- provision/docker/actions_test.go
- provision/docker/container/container.go
- provision/docker/docker_test.go
- provision/docker/provisioner_test.go
- provision/docker/scheduler.go
- provision/docker/scheduler_test.go
- vendor/github.com/tsuru/docker-cluster/cluster/cluster_test.go
- vendor/github.com/tsuru/docker-cluster/cluster/container.go
- vendor/github.com/tsuru/docker-cluster/cluster/container_test.go
- vendor/github.com/tsuru/docker-cluster/cluster/race_test.go
- vendor/github.com/tsuru/docker-cluster/cluster/scheduler.go
- vendor/github.com/tsuru/docker-cluster/cluster/scheduler_test.go
- vendor/github.com/tsuru/docker-cluster/cluster/types_test.go
This avoids the possibility of having multiple containers with the same
name in different nodes due to docker cluster retrying container creation.
> update container name in scheduler

- Makefile
As reported in alecthomas/gometalinter#355, gotype is throwing false positives
for _test pkgs and for function redefinition in different build tags. Examples:
```
cmd/open_darwin.go:9:6:error: open redeclared in this block (gotype)
cmd/open.go:11:6:error: other declaration of open (gotype)
service/bind_test.go:5:1:error: package service_test; expected service (gotype)
```
> Makefile: disable gotype linter

- api/build.go
- api/build_test.go
- api/deploy.go
- api/server.go
- app/deploy.go
- app/deploy_test.go
- app/image/image.go
- builder/builder.go
- builder/docker/actions.go
- builder/docker/builder.go
- builder/docker/builder_test.go
- builder/docker/docker.go
- builder/fake/builder.go
- builder/fake/builder_test.go
- cmd/tsurud/checker.go
- docs/reference/config.rst
- etc/tsuru-compose.conf
- permission/permitems.go
- permission/permlist.go
- provision/docker/image.go
- provision/docker/provisioner_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- provision/swarm/suite_test.go
This PR creates the app-build endpoint, with the purpose of build app images without doing the deploy.
example of use: 
```
$ tsuru app-build -a myapp -t <commit_hash>
registry.domain/myteam/app-myapp:commit_hash
```
This PR is related to #1521
> Add Build Endpoint

- api/app.go
- api/app_test.go
- app/app.go
- app/app_test.go
- router/routertest/router.go
- storage/driver.go
- storage/mongodb/cache.go
- storage/mongodb/cache_test.go
- storage/mongodb/mongodb.go
- storage/mongodb/suite_test.go
- storage/storagetest/cache_suite.go
- storage/storagetest/custom_suite.go
- types/cache/cache.go
Cached value is always used in app-list, if not found or empty a cache refresh will be triggered in background.
app-info will always force a new request to the router and update the cache.
> cache app routers addrs for app list

- provision/kubernetes/helpers.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This allow us to permit Kubelet to register the node while preventing it
from being used by setting a tsuru.io/inprogress NoSchedule taint.
Once the node is registered in tsuru we ensure this taint is removed.
> provision/kubernetes: remove in progress taint from node on add/update

- api/node.go
- api/node_test.go
- event/event.go
> event,api: uses a global targetType for rebalance events without pool filter

- app/app.go
- app/app_test.go
- autoscale/autoscale.go
- autoscale/autoscale_test.go
- provision/docker/containers.go
* Force rebalance if nodes were added as there's no need for the provisioner to check if a rebalance is necessary, with a new empty node it'll always be necessary;
* Wait application lock for a few seconds when calculating units in nodes for autoscale and rebalance, and also when running rebalance;
* When running autoscale checks, try checking if a rebalance is necessary even if new nodes were necessary but adding them failed.
Fixes #1759
> Improvements to node autoscale routines

- provision/swarm/docker.go
- provision/swarm/docker_test.go
This prevented BS container from working correctly with swarm.
> provision/swarm: use network mode specified in node container

- .travis.yml
This was causing errors trying to use a different mongodb version
> .travis: remove unnecessary before scripts

- provision/kubernetes/provisioner.go
This makes easier to integrate with cloudproviders.
> provision/kubernetes: adds iaasID to node.Spec.ProviderID

- api/iaas_test.go
- api/node.go
- api/node_test.go
- autoscale/autoscale.go
- healer/healer_node.go
- provision/node.go
This fixes machines being created without the `<pool>-` prefix.
> Only remove pool metadata after creating machine in iaas

- api/app.go
- api/app_test.go
This is the partial fix for #1772  
Could someone please check if I am using the correct HTTP status below?
```go
return &errors.HTTP{Code: http.StatusForbidden, Message: "Moving apps between pools belonging to different provisioners is not alllowed"}
```
I was in doubt between that status and `http.StatusBadRequest`.
I added a test, but I will remove it once I am done with the final solution discussed in #1772 
Should I add the block containing lines 463-473 to the if block in line 437 in `api/app.go`?
> Forbidding the pool change if the new pool has a different provisioner

- docs/managing/provisioners.rst
There where some typos and a grammar mistake. The word `fewest` should be used instead of `fewer`, since tsuru chooses the node that, among all the nodes, has the smallest number of containers from a given application.
> Enhancing Docs » Managing » Provisioners

- app/app.go
- app/app_test.go
- provision/pool/pool.go
I tried to list the public constraints, but in some test, the pool `pool1` are showing with the team's pools. But it is not initialized in the test scope, maybe it has a global behaviour, but I don't know.
Any suggestion?
Ref https://github.com/tsuru/tsuru/issues/1782
> Include public pools in app creation error

- router/routertest/router.go
Write at 0x000001467538 by goroutine 199:
github.com/tsuru/tsuru/router/routertest.(*fakeRouter).Reset()
/tmp/gopath/tsuru/src/github.com/tsuru/tsuru/router/routertest/router.go:326 +0x193
github.com/tsuru/tsuru/app.(*S).SetUpTest()
/tmp/gopath/tsuru/src/github.com/tsuru/tsuru/app/suite_test.go:128 +0x4f
runtime.call32()
/usr/local/go/src/runtime/asm_amd64.s:514 +0x47
reflect.Value.Call()
/usr/local/go/src/reflect/value.go:302 +0xc0
github.com/tsuru/tsuru/vendor/gopkg.in/check%2ev1.(*suiteRunner).runFixture.func1()
/tmp/gopath/tsuru/src/github.com/tsuru/tsuru/vendor/gopkg.in/check.v1/check.go:721 +0x184
github.com/tsuru/tsuru/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
/tmp/gopath/tsuru/src/github.com/tsuru/tsuru/vendor/gopkg.in/check.v1 …
> router/routertest: fix race in router test

- api/node.go
- api/node_test.go
- provision/node.go
- provision/node_test.go
- provision/provisiontest/fake_provisioner.go
We don't need to check the chosen provisioner because it's expected that
the Provisioner.AddNode call will already handle duplicated cases and
handler then accordingly.
> api,provision: prevent check for node existence in chosen provisioner

- provision/kubernetes/nodecontainer.go
- provision/kubernetes/nodecontainer_test.go
- provision/swarm/docker.go
- provision/swarm/provisioner.go
With multiple clusters every bind added to the node container config would
persist on the next cluster since we were modifying a config's pointer.
> provision/kubernetes: fix node containers with multiple clusters

- api/app.go
- api/pool_test.go
- app/app.go
- app/suite_test.go
- provision/docker/provisioner.go
- provision/docker/suite_test.go
- provision/kubernetes/provisioner.go
- provision/pool/constraint.go
- provision/pool/constraint_test.go
- provision/pool/pool.go
- provision/pool/pool_test.go
- provision/pool/provcache.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- provision/swarm/provisioner.go
The performance degradation comes mainly from querying each provisioner for units of each individual application.
The first part of this PR caches the Provisioner value for each Pool in memory as this value cannot be changed for an existing pool.
The second part involves changing the Provisioner.Units interface method to allow querying units from multiple apps in a single call.
> Improve app-list performance

- event/event.go
- event/event_test.go
- event/migrate/migrate_test.go
- provision/docker/containers.go
```
Read at 0x00c4221ecda0 by goroutine 320:
github.com/tsuru/tsuru/event.(*Event).Write()
/tmp/gopath/tsuru/src/github.com/tsuru/tsuru/event/event.go:941 +0x4b
fmt.Fprintf()
/usr/local/go/src/fmt/print.go:182 +0xc7
github.com/tsuru/tsuru/provision/docker.(*dockerProvisioner).MoveOneContainer()
/tmp/gopath/tsuru/src/github.com/tsuru/tsuru/provision/docker/containers.go:194 +0x12b5
Previous write at 0x00c4221ecda0 by goroutine 395:
github.com/tsuru/tsuru/provision/docker.(*dockerProvisioner).MoveOneContainer()
/tmp/gopath/tsuru/src/github.com/tsuru/tsuru/provision/docker/containers.go:202 +0xf8c
Goroutine 320 (running) created at:
github.com/tsuru/tsuru/provision/docker.(*dockerProvisioner).moveContainerList() …
```
> event,provision/docker: fix race updating writer for existing event

- api/router.go
- api/router_test.go
- app/app.go
- app/app_test.go
- router/router.go
- router/routertest/router.go
- types/app/app.go
This adds router info to /routers (tsuru router-list) calls, and status information to /apps/{} and /apps/{}/routers (app-info, app-router-list).
> Add information about router info and status to api returns

- integration/install_test.go
Using iptables instead of machine-destroy to force the healing of
a allows using kubernetes with a cloudprovider that keeps track of nodes
and machines, since removing the machine with `machine ddestroy` would
cause the node to be removed from the kubernetes cluster by the
cloudprovider (this causes the machine to never get healed as tsuru has
no way to known that such node existed in the first place).
> integration: uses iptables to remove conectivity between node and api

- Gopkg.lock
- provision/docker/nodecontainer/queue.go
- provision/docker/provisioner_test.go
- vendor/github.com/tsuru/docker-cluster/cluster/cluster.go
The race condition can still happen, however it won't corrupt node pool
metadata information nor the creation status.
> provision/docker: mitigate race when a node is removed and added again

- action/action.go
- action/action_test.go
- action/stubs_test.go
Ideally, one action should never panic but this change makes sure we
handle it gracefully (calling the backwards function as when an error occurs)
to minimize the chance of inconsistences.
> action: handle panics as errors during pipelines

- iaas/dockermachine/iaas.go
- iaas/dockermachine/iaas_test.go
Since the iaas implementation derives the machine name from the pool
and tsuru doesn't ensure that the pool is a valid hostname, the
implementation must strip any invalid character from the pool name
before generating the machine name.
> iaas/dockermachine: ensure machine name is valid hostname

- builder/docker/builder_test.go
```
Read at 0x00c42042a090 by goroutine 9:
github.com/tsuru/tsuru/builder/docker.(*S).TestBuilderImageIDWithTsuruYaml.func1()
/home/travis/gopath/src/github.com/tsuru/tsuru/builder/docker/builder_test.go:360 +0x205
net/http.HandlerFunc.ServeHTTP()
/home/travis/.gimme/versions/go1.9.linux.amd64/src/net/http/server.go:1918 +0x51
github.com/tsuru/tsuru/vendor/github.com/fsouza/go-dockerclient/testing.(*DockerServer).ServeHTTP()
/home/travis/gopath/src/github.com/tsuru/tsuru/vendor/github.com/fsouza/go-dockerclient/testing/server.go:336 +0x1ff
net/http.serverHandler.ServeHTTP()
/home/travis/.gimme/versions/go1.9.linux.amd64/src/net/http/server.go:2619 +0xbc
net/http.(*conn).serve()
/home/travis/.gimme/versions/go1.9.linux.amd64/src/net/http/server.go:1801 …
```
> builder/docker: fix race condition in tests

- builder/docker/builder.go
- builder/docker/builder_test.go
- builder/docker/platform.go
- docs/using/tsuru.yaml.rst
- provision/provision.go
Set deploy hooks when deploying from an image
> Image deploy hooks

- api/app.go
- api/app_test.go
- db/storage.go
- event/event.go
- event/event_test.go
- event/eventlist_test.go
- event/eventtest/checker.go
- healer/healer_node.go
- healer/healer_node_test.go
- provision/docker/healer/healer_container.go
- provision/docker/healer/healer_container_test.go
Now the following events have multiple targets:
app.swap -> target: app1, extra-targets: app2
container healer -> target: failing container, extra-targets: new-container, app
node healer -> target: failing node, extra-targets: new-node, pool
> Allow events with multiple targets

- router/api/generator/combinations.go
- router/api/router_test.go
- router/api/routeriface.go
Enable routers of type API to have routerOpts interface. 
This will allow us to use specific parameters on API routers, as using kubernetes-routes to get some opts and use as 'Host' on ingress to be consumed by nginx-ingress.
> Enabling router opts on API routers

- event/event.go
- event/event_test.go
When `since` or `until` filters are defined, other filters are being ignored
> event: fix event list with time filters

- healer/healer_node.go
- healer/healer_node_test.go
- provision/docker/healer/healer_container.go
- provision/docker/healer/healer_container_test.go
This prevents a single set of nodes or containers from starving other
resources waiting to be healed. Today this can happen due to events rate
limiting only allowing a fixed number of healing events to run
concurrently. If the chosen resources fail to heal the healer process
would select them again as the first they would still be the first
elements in the collection.
> healer,provision: rotate slices with resources for healing

- iaas/cloudstack/iaas_test.go
Example of a race caught by the race detector:
```
Read at 0x00c42021dd40 by goroutine 67:
github.com/tsuru/tsuru/iaas/cloudstack.(*cloudstackSuite).TestCreateMachineAsyncFailure()
/home/travis/gopath/src/github.com/tsuru/tsuru/iaas/cloudstack/iaas_test.go:140 +0x5dc
runtime.call32()
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:509 +0x3a
reflect.Value.Call()
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/reflect/value.go:302 +0xc0
github.com/tsuru/tsuru/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
/home/travis/gopath/src/github.com/tsuru/tsuru/vendor/gopkg.in/check.v1/check.go:772 +0x9ab
github.com/tsuru/tsuru/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1() …
```
> iaas/cloudstack: fix race condition by waiting for queue to finish

- provision/kubernetes/deploy.go
This also improves the error messages as the String method will return
the full received data
> provision/kubernetes: use json unmarshal byte slice already in memory

- provision/kubernetes/helpers.go
- provision/kubernetes/nodecontainer.go
- provision/kubernetes/nodecontainer_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
Instead of setting the node to NoSchedulable we add a taint to the node
to prevent new nodes from being scheduled to the node. Setting the
NoSchedulable flag to the node spec has the undesirable effect of
removing that node from the list of nodes used by LoadBalancers.
> kubernetes: add taint on node disable

- provision/kubernetes/cluster.go
- provision/kubernetes/cluster_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/suite_test.go
This PR adds memory overcommit to Kubernetes cluster by
requesting a fraction of the application memory limit.
For example, with a cluster/pool configure with
overcommit-factor = 2, the request memory will be half of
the application plan and thus allow a 2x memory overcommit.
> provision/kubernetes: enable memory overcommit

- event/event.go
- event/workers.go
- event/workers_test.go
Before this commit the added test case would break due to the 10 buffer
in both addCh and removeCh channels. These buffers allowed the
possibility of a removeCh message to arrive before a addCh message for
the same ID, causing the message to never be removed from the internal
ID Set.
Simply removing the buffer could potentially cause performance issues
as every operation on events (New, Done, etc) would require the
lockUpdater goroutine to be running and unblocked. Long mongodb update
operations could delay the processing of seemingly unreleated events for
a long period of time.
This new approach uses a mutex based approach to update an internal
event ID Set and operations to the Set are made on the same goroutine as
the caller. The lockUpdater goroutine simply reads a copy of the …
> event: ensure updates to lockUpdater internal set are atomic and synced

- auth/oauth/oauth.go
- integration/gce.go
- integration/gce_client.go
- provision/dockercommon/docker.go
Since Go 1.7, context is available as a standard library
> all: replace golang.org/x/net/context imports with context

- docs/managing/add-platform.rst
**Python3** [page](https://github.com/tsuru/platforms/tree/master/python3) doesn't exists anymore.
> Merging python2 and python3 on plataform list 

- api/app.go
- api/service.go
- api/service_instance.go
- app/app.go
- app/app_test.go
- app/bind_test.go
- service/actions.go
- service/actions_test.go
- service/bind_test.go
- service/endpoint.go
- service/endpoint_test.go
- service/service.go
- service/service_instance.go
- service/service_instance_test.go
- service/service_test.go
User and Event ID are sent in all non-GET requests to service endpoints,
also the request ID header was missing from the bind/unbind-app requests
as was added in this PR.
For proxy requests the user and event IDs are sent as a header value
(X-Tsuru-User/Eventid) to preserve the original message body.
> api,app,service: add user and eventid to all service requests

- provision/kubernetes/deploy.go
- provision/kubernetes/helpers.go
On containers started with TTY: true, kubernetes 1.9+ will automatically
try to attach with TTY enabled. This causes a problem if stderr is also
set on the attach call because stderr and tty cannot both be enabled on
the same attach call.
> provision/kubernetes: attach with tty on containers started with tty

- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
This commit disables fetching logs from a failed Pod as this can result
in an unhelpful message in case the node is running docker with an
custom log driver.
> provision/kubernetes: disable trying to fetch logs from failed pod

- provision/kubernetes/builder.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/provisioner.go
This allow us to correctly attach to the pod before any output is lost.
> provision/kubernetes: wait stdin on deploy pod startup

- api/server.go
- api/server_test.go
- api/shutdown/shutdown.go
There was a chance of the server exiting before the shutdown handlers
were called, potentially causing inconsistencies. Also a failure during
startup didn't call the shutdown handlers already registered. This was
fixed now.
> api: ensure servers are shutdown before tsuru shutdown handlers are called

- provision/kubernetes/helpers.go
- provision/kubernetes/provisioner.go
This commit removes a hack that became obsolate since
(https://github.com/kubernetes/kubernetes/commit/fb7674673f484123e92baf6c708cabfc1e15ed79).
Requires Kubernetes 1.7+.
> provision/kubernetes: removes hack to refresh nodes after update

- builder/docker/builder_test.go
- builder/kubernetes/builder_test.go
- docs/using/tsuru.yaml.rst
- net/client.go
- provision/docker/healthcheck.go
- provision/docker/healthcheck_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/provision.go
- provision/swarm/healthcheck.go
- provision/swarm/healthcheck_test.go
- provision/swarm/provisioner_test.go
This PR adds support for custom schemes on the healthcheck. In all provisioners,
certificate validation is skipped (this is the behavior for kubernetes probes).
We should probably consider exposing the scheme to be used on the router healthcheck.
> provision: enable configuring custom scheme for healthcheck

- builder/docker/actions.go
- builder/docker/actions_test.go
- provision/docker/actions.go
- provision/docker/actions_test.go
- provision/docker/container/container.go
- provision/docker/container/container_test.go
- provision/docker/provisioner_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/swarm/docker.go
- provision/swarm/provisioner_test.go
This PR is related to #1945. Now, whenever you deploy a new version of your app, you can pull the last image using the tag `latest`.
> builder,provision: adding the latest tag to deploy image

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/testing/reaction.go
- provision/labels.go
Router info may contain ',' characters, which are invalid in labels.
Fixes #1982
> provision/kubernetes: move router related labels to annotations

- api/suite_test.go
- app/app.go
- app/routerupdater.go
- app/routerupdater_test.go
- app/suite_test.go
- autoscale/autoscale_test.go
- provision/docker/suite_test.go
- provision/servicecommon/actions_test.go
- repository/gandalf/gandalf_test.go
This allow us to limit the number of concurrent calls to the router and
to add a shutdown handler waiting for pending goroutines before
terminating the tsuru process.
This PR also update tests which call app.List to ensure the created
goroutines are finished after each test case.
> app: control lifecycle of goroutines in app.List to update router addrs

- api/app.go
- api/app_test.go
The contentHijacker middleware uses ajg/form to decode/encode a json
request into a form data. This serializes arrays in its own, weird,
format, e.g: "array.0=x", "array.1=y" etc. To be able to fully support
this hijacker on app creation, this PR makes those endpoints compatible
with both formats.
> api/app: support tags from json body on app create/update

- api/server.go
- app/cache.go
- app/plan.go
- app/platform.go
- auth/suite_test.go
- auth/team.go
Returning an error is way better then an unexpected panic during
runtime.
> api,app,auth: refactor service creation funcs to also return error

- app/plan.go
The planService `DefaultPlan()` method is racy. When two apps are created
in parallel there is a chance that we try to insert the "autogenerated"
plan multiple times, failing with: `Error: plan already exists`.
This commit adds a check to validate that after a "plan already exists"
error we are able to retrieve a default plan and return it.
This was caught by our integration tests which create apps in parallel.
> app: handle race during default plan creation

- provision/cluster/cluster.go
- provision/cluster/cluster_test.go
- provision/kubernetes/cluster.go
When tsuru API is running in a Kubernetes cluster, try to get the cluster configs automatically when registering it.
> Get Kubernetes cluster config automatically when running in cluster

- provision/env.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/labels.go
- provision/labels_test.go
This commit removes the "replicas" label from pods. Without this change,
adding/removing a single (or multiple units) from an app would cause
Kubernetes to behave the same as when a new deploy happens (creating
a new replicaset, doubling the number of units during the operation).
I considered keeping the pod labels to a minimum (probably only the set of
labels used on the selector) but this would require some large change on the way
the provisioner returns the units to tsuru. What do you think, @cezarsa?
> provision/kubernetes: drops replicas label from pods

- provision/pool/constraint.go
- service/service.go
The MatchString call in the pool pkg was responsible for over 500GB of allocations alone, causing the second largest flat allocation node in a production profile:
```
(pprof) top
Showing nodes accounting for 818.74GB, 53.66% of 1525.77GB total
Dropped 1988 nodes (cum <= 7.63GB)
Showing top 10 nodes out of 247
flat  flat%   sum%        cum   cum%
196.45GB 12.88% 12.88%   211.47GB 13.86%  github.com/tsuru/tsuru/vendor/github.com/globalsign/mgo.(*mongoSocket).readLoop
117.10GB  7.67% 20.55%   117.10GB  7.67%  regexp/syntax.(*compiler).rune
```
```
(pprof) peek regexp.MatchString
Showing nodes accounting for 1562389.06MB, 100% of 1562389.06MB total
----------------------------------------------------------+-------------
flat  flat%   sum%        cum   cum%   calls calls% + context …
```
> Pre-compile regexps in service and provision/pool pkgs

- Dockerfile.build
- build-compose.sh
This PR adds a local Dockerfile to be used by compose-build when building tsuru
for development. Our alpine platforms are not really maintained right now and
updating Go was getting harder and harder. For that reason, this local Dockerfile
relies on Go's official image.
> compose: adds local Dockerfile for build

- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
selector.Add actually returns a new Selector with the added requirement
instead of mutating the existing requirements. Before this change, the
API would send an empty list of requirements resulting in every pod
being listed.
> provision/kubernetes: fixes Units failing to list app units

- api/deploy.go
- api/event.go
- cmd/cmd.go
- cmd/cmd_test.go
- docs/reference/api.yaml
This PR adds support for canceling running commands by using SIGINT. The command
must implement the Cancelable interface and handle the cancelation making sure its on
a sane state.
> cmd: add support for signaling command cancellation

- cmd/cmdtest/transport.go
- cmd/cmdtest/transport_test.go
This is required for some tsuru-client tests for deploy cancellation
> cmd: adds ReadCloser transport

- api/server.go
- api/webhook.go
- api/webhook_test.go
- docs/reference/api.yaml
- event/event.go
- event/eventlist_test.go
- event/webhook/webhook.go
- event/webhook/webhook_test.go
- net/client.go
- permission/permitems.go
- permission/permlist.go
- servicemanager/servicemanager.go
- storage/driver.go
- storage/mongodb/mongodb.go
- storage/mongodb/webhook.go
- storage/mongodb/webhook_test.go
- storage/storagetest/webhook_suite.go
- types/event/webhook.go
- validation/validation.go
WebHooks can now be registered in the tsuru API to be triggered whenever an event matches the webhook specification.
The two main parts for this PR are:
1 - Routes for WebHooks CRUD and corresponding service and storage methods.
2 - Each time an event is finished (`evt.Done()` call), tsuru will send to event to a channel where a dedicated goroutine will pick the event and search for all webhooks matching it. After listing all webhooks that must be called tsuru will proceed to call them sequentially.
By default the webhook request is a POST containing in its body the event that triggered it serialized as JSON, but this behavior can be overridden by setting a custom method and body in the event.
> Add support for webhooks triggered on events

- provision/docker/image_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
If a Kubernetes service is not found, app routes rebuild command is setting the port to `0`. With this PR, it fails and doesn't change the routes.
> provision/kubernetes: return err instead of port 0 when service is not found

- docs/managing/volumes.rst
- etc/tsuru-compose.conf
Add an exemple of hostPath persistent volume configuration with minikube, and a volume plan for docker compose.
> docs: add example of volumes usage with minikube

- builder/docker/builder.go
- builder/docker/platform.go
- provision/docker/actions_test.go
- provision/docker/clusterclient/clusterclient.go
- provision/docker/container/container.go
- provision/docker/containers.go
- provision/docker/dockertest/provisioner.go
- provision/docker/dockertest/provisioner_test.go
- provision/docker/image.go
- provision/docker/nodecontainer/nodecontainer.go
- provision/docker/provisioner_test.go
- provision/dockercommon/docker.go
- provision/swarm/docker.go
Also image pull calls for node-containers and app-run --isolated were
missing pull auth parameters.
> provision/docker: only set auth if image belogs to registry in config

- api/app_test.go
- api/shell.go
- api/shell_test.go
- app/app.go
- app/app_test.go
- cmd/shell.go
- provision/docker/container/container.go
- provision/docker/container/container_test.go
- provision/docker/containers.go
- provision/docker/provisioner.go
- provision/docker/provisioner_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/helpers.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- provision/provisiontest/fake_provisioner_test.go
- provision/swarm/docker.go
- provision/swarm/provisioner.go
- provision/swarm/provisioner_test.go
- vendor/github.com/tsuru/docker-cluster/cluster/container.go
Unifying all previous methods allow us to simplify the logic behind each
implementation. Now the differece between app-shell and app-run is
simply the presence of a Stdin reader in the ExecuteCommand call. This
change also removes some logic from inside each provisioner and moves it
to the `app` package, allowing it to be shared (selecting which units to
run and which commands to be executed).
Another benefit is that we now also have `app-shell --isolated` almost
for free.
Fixes #1827
> api,app,provision: single ExecuteCommand implementation in provisioners

- api/node.go
- autoscale/autoscale.go
- provision/docker/provisioner.go
- provision/docker/scheduler.go
- provision/env_test.go
- provision/kubernetes/provisioner.go
- provision/node/node.go
- provision/node/node_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- provision/swarm/provisioner.go
This PR moves existing node logic from the provision pkg to a newly created node pkg. Now, instead of handling healer data removal from inside the provisioner this logic was added to a RemoveNode method in the node pkg.
> provision: ensure node removal removes healer data for node

- provision/kubernetes/provisioner.go
The In operator cannot be user as a fieldSelector, only as
labelSelector, this code was only working because the returned Set with
the Requirement applied was being incorrectly ignored.
> provision/kubernetes: fix nodes filtering, In operator isn't valid

- cmd/tsurud/migrate.go
- provision/kubernetes/migrate/migrate.go
- provision/kubernetes/migrate/migrate_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This commit adds a required migration that is responsible for
ensuring that every kubernetes application has a corresponding
app CRD created on the cluster. This is done by calling the
provision.Provision method on the app.
> provision/kubernetes,cmd: adds migration for kubernetes apps

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
Only rollback deployments if the revision was updated and correctly list new pods to start healthcheck timeout.
> provision/kubernetes: fix in deployment rollback and monitoring

- api/service_instance.go
- api/service_instance_test.go
- service/service_instance.go
- service/service_instance_test.go
This route returns a modified service instance struct containing the
Info map returned by the service API
> api,service: fix compatibility of /services/{name} api route

- provision/kubernetes/deploy_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This change updates the default deploy-agent to 0.5.0. This version
contains better handling of environment variables, fixing parsing of
environment variables that contain quotes.
> provision/kubernetes: updates default deploy-agent to 0.5.0

- app/actions.go
- app/actions_test.go
- app/app.go
- app/app_test.go
- builder/kubernetes/suite_test.go
- etc/tsuru-compose.conf
- provision/kubernetes/actions.go
- provision/kubernetes/builder.go
- provision/kubernetes/builder_test.go
- provision/kubernetes/cluster.go
- provision/kubernetes/cluster_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/migrate/migrate_test.go
- provision/kubernetes/node_test.go
- provision/kubernetes/nodecontainer.go
- provision/kubernetes/nodecontainer_test.go
- provision/kubernetes/pkg/apis/tsuru/v1/types.go
- provision/kubernetes/pkg/apis/tsuru/v1/zz_generated.deepcopy.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/suite_test.go
- provision/kubernetes/testing/reaction.go
- provision/kubernetes/volume.go
- provision/kubernetes/volume_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- provision/provisiontest/fake_provisioner_test.go
This PR adds support for app pool update accross different kubernetes clusters
and also accross a single cluster configured with per pool namespaces.
> provision/kubernetes: support app pool update with multiple namespaces

- api/server.go
Shell scripts snippets like 
```
token=$(tsurud token)
```
are broken due this msgs being print to stdout.
> Using stderr for warning messages on server

- app/app.go
Some routers may require that the application is already provisioned
to be able to add the backend.
> app: provision app before adding backend to router

- provision/kubernetes/helpers.go
Doesn't solve #1735, but addresses it a bit since the lack of information on why the cleanUp failed on deleting the pods make the issue a bit more obscure.
> Adding logging to cleanupPod, as it only called from defer.

- api/service_broker_test.go
- api/service_instance.go
- api/service_instance_test.go
- service/broker.go
- service/broker_service.go
- service/broker_test.go
- service/plan.go
- service/service_instance.go
- service/service_instance_test.go
- storage/storagetest/service_broker_suite.go
- types/service/broker.go
Service from the Service Broker API support custom parameters for
instance creation and binding. This PR adds the parameters definition
to the Plan information and make it possible for the client to show them.
This PR continues the work done in #2086.
> service: Adds plan schemas to service API responses

- api/service_broker_test.go
- app/app.go
- app/app_test.go
- app/bind/binder.go
- provision/provisiontest/fake_provisioner.go
- service/actions.go
- service/actions_test.go
- service/broker.go
- service/broker_service_test.go
- service/broker_test.go
- service/service_instance.go
- storage/storagetest/service_broker_suite.go
- types/service/broker.go
Service Brokers requires that GUIDs and IDs are actual v4 UUIDs.
This PR creates a UUID field that is lazily generated for apps,
generates UUIDs for service instances and also stores broker instances
data inside the service instance data structure.
> service/broker: Uses UUIDs for service broker operations

- service/broker.go
- service/broker_test.go
Use acceptsIncomplete in service broker operations to notify the
broker about async support.
> service/broker: defaults to async operations

- provision/kubernetes/cluster.go
- provision/kubernetes/cluster_test.go
- provision/kubernetes/helpers.go
Kubernetes namespaces don't allow underscores. Tsuru pool names don't either, but they did in previous versions. This PR avoids problems with pool names that contain this character.
> provision/kubernetes: replace invalid characters from pool name

- api/apitest/setup.go
- docs/reference/config.rst
- net/client.go
- router/galeb/client/galeb.go
- router/galeb/client/galeb_test.go
- router/galeb/router.go
- service/endpoint.go
We now use a connection pool to talk to both galeb and service APIs, also galeb API GETs are retried after errors.
Also a new config flag was added to the Galeb router to limit the number of parallel connections.
With @guilhermebr.
> Improve resilience when talking with galeb router api and service APIs.

- router/galeb/client/galeb.go
- router/galeb/client/galeb_test.go
- router/galeb/router.go
- router/galeb/router_test.go
This change will ensure the routes rebuild routine always create missing
or partially created resources.
> router/galeb: ensure all resources are created even after a 409 response

- api/auth_test.go
- auth/native/suite_test.go
- auth/native/user_test.go
- auth/suite_test.go
Our test server does not support AUTH messages and after https://go-review.googlesource.com/c/go/+/79776 introduced in Go 1.11, sending AUTH messages to a server that does not support them returns an error.
> api,auth/native: remove smtp password from email tests

- api/server.go
- api/shutdown/shutdown.go
This is needed because some shutdown handlers are required for allowing a clean shutdown of the server. One suck example is the app-log -f shutdown handler which will close existing log connections.
This commit also fix a race where if a stop signal is triggered before the server is listening the shutdown handlers would run but the server would still start and listen for connections.
Fixes #2050.
> api: run shutdown handlers alongside server stop

- provision/kubernetes/cluster.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
Main motivation is easy interop with tools that require specific labels in the namespace like Istio which requires a `istio-injection=enabled` label.
> provision/kubernetes: accept custom labels for created namespaces

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
The 'app' label has become an unofficial standard, its used on many deployments in the wild and some tools have come rely on it, such as Istio. Reference https://istio.io/docs/setup/kubernetes/spec-requirements/.
> provision/kubernetes: add 'app' label to tsuru deployments

- api/node_test.go
- app/app.go
- app/app_test.go
- healer/healer_node.go
- healer/healer_node_test.go
- provision/node/node_test.go
- provision/provisiontest/fake_provisioner.go
This PR changes the healer to try finding an existing node with the received addrs if the provisioner errored when trying to find the node. This will ensure a provisioner outage doesn't impact its nodes.
> app,healer: try updating node status even if provisioner is unavailable

- cmd/client.go
- cmd/transport.go
- cmd/transport_test.go
Prior to this change, the client object was responsible for providing
the request/response dumping according to the given verbosity level.
Commands using the new go-tsuruclient (generated from the spec) didn't
support the verbosity parameter because they do not use Client.
This change implements a custom RoundTripper that provides
request/response dumping according to a verbosity level. Commands
implemented with the new client simply have to pass down the http.Client
to the go-tsuruclient instance.
> cmd: implements verbosity inside a custom RoundTripper

- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This change introduces a sync that makes sure the app custom resource is
properly synced before doing any operation inside the Kubernetes
cluster.
> provisioner/kubernetes: sync app CR before changing state

- builder/kubernetes/suite_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/suite_test.go
- provision/kubernetes/testing/reaction.go
Now on a normal app-list operation it's not expected for any api call to the Kubernetes API.
> provision/kubernetes: use informers for service and nodes

- provision/cluster/cluster.go
- provision/cluster/cluster_test.go
- provision/kubernetes/cluster.go
- provision/kubernetes/cluster_test.go
- provision/kubernetes/node_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/suite_test.go
- types/provision/cluster.go
- types/provision/cluster_mock.go
This was acomplished by creating a new FindByPools method in the cluster service and not filtering which units we show ports anymore, if a Unit has a service pointing to it we'll show the service port.
> provision/kubernetes: only query tsuru database once in Units call

- api/service_broker.go
- api/service_broker_test.go
- docs/reference/api.yaml
- service/broker_catalog_cache.go
- service/broker_catalog_cache_test.go
- service/broker_service.go
- service/broker_service_test.go
- types/service/broker.go
The previous `CacheExpiration *time.Duration` field was hard to manipulate in the api. In this PR, this field is replaced with `CacheExpirationSeconds int`. The logic to convert strings like `5m` to seconds will be done in the client.
Also, change the service broker update logic to keep the previous value when `CacheExpirationSeconds` is zero, and change to the default value when it's negative.
> Replace CacheExpiration field service broker catalog cache with CacheExpirationSeconds

- router/galeb/router.go
- router/galeb/router_test.go
During AddBackend calls started by the routes rebuild process, if an API call failed with an error different from 409 there was the possibility of tsuru completely removing the backend and all it's routes.
This commit fix this behavior and only removes existing resources if we're dealing with a new backend.
> router/galeb: fix bug where an existing router would be deleted

- api/app.go
- api/app_test.go
- app/app.go
- app/app_test.go
Kubernetes validates env var names, which may result in errors when an app is migrated from Docker cluster to Kubernetes.
The Kubernetes regexp to validate env vars is `[-._a-zA-Z][-._a-zA-Z0-9]*`, which allows var names like `----` and `.`. I decided to make a more restrictive validation, ensuring the first character is a letter and avoiding dots.
This fixes #2144
> Add validation to environment variable names 

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
Prior to this change, if the first deploy of an app fails, tsuru would not properly rollback the Deployment. In this case, the correct rollback procedure would be to delete Deployment.
This change checks if the current operation created a Deployment object
and deletes it after the operation fails.
Fixes #2132.
> provision/kubernetes: handle deployment rollback on first deploys

- api/app_test.go
- api/volume.go
- api/volume_test.go
- app/app.go
- app/app_test.go
- app/platform_test.go
- auth/team_token_test.go
- event/webhook/webhook.go
- event/webhook/webhook_test.go
- provision/cluster/cluster.go
- provision/cluster/cluster_test.go
- provision/kubernetes/builder.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/volume_test.go
- provision/pool/pool.go
- provision/pool/pool_test.go
- provision/swarm/volume_test.go
- service/service.go
- service/service_test.go
- types/app/platform.go
- validation/validation.go
- validation/validation_test.go
- volume/volume.go
- volume/volume_test.go
Change name validation rules to avoid incompatibilities with Kubernetes:
- reduce max length to 40 characters for app, platform, team token id, event webhook, pool, cluster, volume and service
- remove `tsuru-app-` prefix from `app` label in deployments and pods, to save some characters (label values can't have more than 63 characters)
- limit service and deployment names to 55 characters (max length allowed by Kubernetes is 63 characters). If `<app name>-<process name>`has more than 55 characters, replace the process name with a sha256 hash
This fixes #2145.
> Improve name validation for Kubernetes

- app/image/image.go
- app/image/image_test.go
Prior to this change, `GetImageWebProcessName` would return "web" if the
application had more than a single process, even if none of them was
actually called "web". This causes a issue on the Kubernetes provisioner
because it relies on the returned name to find some cluster resources,
causing the `RoutableAddresses()` method to fail.
This change makes sure that `GetImageWebProcessName` always return a
existing process name. If the application has more than a single process
it will either return "web", if one of them is called "web", or the
first process in alphabetical order.
Fixes #2165
> app/image: always return a existing process on GetImageWebProcessName

- docs/contributing/compose.rst
The node IP that is registered should be the internal IP, not the minikube VM IP.
> docs: fix instructions for minikube setup

- etc/tsuru-compose.conf
build-compose.sh file creates an IP alias to docker interface (10.200.10.1), 
this alias is used by registry container.
in order to  Tsuru API can reach and use Tsuru apps, a router to this alias is needed.
This PR adds the router 10.200.10.1.nip.io:8989 to etc/tsuru-compose.conf
an example of this is setting tsuru/healthcheck-as-a-service app as a Tsuru service.
example of haas service.yml:
```
id: healthcheck
password: abc123
team: admin
endpoint:
production: hcaas.10.200.10.1.nip.io:8989
```
> Dev: Add docker ip alias to compose file

- app/app.go
- app/app_test.go
Prior to this change, users could not filter apps that were using a
specific plataform version (locked).
This change makes it possible to filter apps that are locked to a
specific platform version or are not locked to a specific version. Usage
is as follows:
`app list -p go` -> returns all apps using go (locked or not)
`app list -p go:v1` -> returns all apps that are using go locked to the
v1 version
`app list -p go:latest` -> return all apps that are not locked to a
specific go platform version.
> app: enable filtering apps with specific platform versions

- api/app.go
- api/app_test.go
- docs/reference/api.yaml
This is my attempt to fix issue #2138 
I added a new flag: `nameOnly`. If the flag is present and true, then it returns a JSON with an array of app names in the form: 
```
[
{"name": "app-name1"},
{"name": "app-name2"}
]
```
It also skips the query for the app unit status.
I also added one test case to check the flag does not break the current interface implementation.
> api: add nameOnly flag to apps endpoint

- provision/kubernetes/deploy.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/testing/reaction.go
This change allows tsuru to ignore containers added by admission controllers that may never reach the desired state.
> provision/kubernetes: only wait for containers managed by tsuru

- router/galeb/client/galeb.go
- router/galeb/router_test.go
- router/galebv2/client/galeb.go
- router/galebv2/router_test.go
Before this commit, if an error occurred while doing concurrent requests to the galeb API we would return before waiting for pending goroutines to finish. This could cause unexpected behaviors.
> router/galebv2: wait for all goroutines to finish before returning

- errors/errors_test.go
I improved the coverage for the `errors` package.
The coverage in the package was 43%. Now it is 100%.
> Test for errors package

- api/app.go
- api/app_test.go
- provision/kubernetes/nodecontainer_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/testing/reaction.go
Currently we don't support moving volumes between namespaces of a Kubernetes cluster. This PR adds a validation to prevent this.
Moving between different clusters works fine.
> Kubernetes: apps with binded volumes can't change namespaces

- provision/kubernetes/helpers.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
Prior to this change, every label/annotation added to a node thru the
metadata fields would contain the "tsuru.io/" prefix. This makes it hard
to use the metadata field as a way to add annotations and labels
required by some Kubernetes components.
This change introduces two special metadata fields:
"tsuru.io/extra-labels" and "tsuru.io/extra-annotations". Each of these
fields may contain multiple key and values that are applied as is as
labels ou annotations on a Kubernetes node.
> provision/kubernetes: adds a way to append labels/annotations as is

- docs/advanced_topics/node_scaling.rst
- docs/installing/gandalf.rst
- docs/managing/logs.rst
Description of the change: Corrects the dots usage in the node_scaling.rst, gandalf.rst and logs.rst files.
Reason for the change: In the texts of the files are missing points.
Link to original source:
https://github.com/tsuru/tsuru/blob/master/docs/installing/gandalf.rst
https://github.com/tsuru/tsuru/blob/master/docs/advanced_topics/node_scaling.rst
https://github.com/tsuru/tsuru/blob/master/docs/managing/logs.rst
> docs: fix dot usage in docs

- docs/advanced_topics/metrics.rst
- docs/services/api.rst
- docs/services/open-service-broker.rst
**Description of the change**: Corrects typos in metrics.rst, api.rst and open-service-broker.rst.
**Reason for the change**: Typos in the doc files.
**Link to original source**: 
https://github.com/tsuru/tsuru/blob/master/docs/advanced_topics/metrics.rst
https://github.com/tsuru/tsuru/blob/master/docs/services/api.rst
https://github.com/tsuru/tsuru/blob/master/docs/services/open-service-broker.rst
> docs: fix typos in docs

- build-compose.sh
This fixes running the script when `GOPATH` env var isn't defined.
> build-compose.sh: get GOPATH with `go env`

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This is useful to avoid port conflicts with other services when using
Isitio, due to a limitation on how istio handles headless services.
> provision/kubernetes: allow custom headless service port

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
The version label can be used by istio or other components.
> provision/kubernetes: add version label to deployments and app to svcs

- Makefile
- api/server.go
- api/server_test.go
- docker-compose.yml
- docs/reference/config.rst
- etc/tsuru-custom.conf
- etc/tsuru.conf
Prior to this change, it was needed to restart the web server to provide the newer TLS certificates on disk. That's bad practice because involves downtime of service.
This change allows that TLS certificates will be reloaded on runtime by the web server. That reload process occurs ever than the certificates on disk are different of the currently in-memory. The frequency of this process is defined by "tls:auto-reload:interval" setting on the configuration file.
> Support TLS certificate hot-reload

- api/app.go
- api/nodecontainer.go
- api/volume.go
- provision/docker/handlers.go
This PR redirects the log of multiple different events to the event object itself. This guarantees that the log is going to be persisted into the storage.
> api,provision/docker: store logs for multiple types of events

- app/actions.go
- app/app.go
This PR aims to reduce the downtime during an app update that involves different provisioners. Routers are set to nil during the add unit process to make sure that we only rebuild the app routes after the entire process is finished.
A final routes rebuild is always called to make sure that we don't miss anything.
> Reduces downtime during updates between diff provisioners

- api/app_test.go
- api/build_test.go
- api/deploy_test.go
- api/event_test.go
- api/suite_test.go
- app/actions.go
- app/actions_test.go
- app/app.go
- app/app_test.go
- app/log.go
- app/log_test.go
- app/suite_test.go
- db/storage.go
- db/storage_test.go
MongoDB collections for app logs are created as [capped collections](https://docs.mongodb.com/manual/core/capped-collections/). But if the collection creation fails for any reason, the error is ignored, and the first insert ends up creating the collection, but uncapped.
With this PR, the app log collection is created on the app creation.
> api,app,db: create log collection on app creation

- cmd/oauth.go
This ensures that the client won't exit before the http response was
completely flushed, as this would cause the browser to show a connection
error.
> cmd: wait for server shutdown before returning

- api/cluster.go
- api/cluster_test.go
- types/provision/cluster.go
This ensures that we can set the cluster's clientkey while removing it in the list response.
> api: Allow (de)serialization of cluster client key as json

- docs/using/docker-image.rst
This pull will add documentation details about the deploy process with plain Docker images.
Outline:
- do not expose a port in Docker image
- listen to $PORT env var
> Add documentation about Docker image deploy

- action/action.go
- app/app.go
- app/deploy.go
- app/image/image.go
- app/image/image_test.go
- app/image/migrate/migrate.go
- app/image/migrate/migrate_test.go
- builder/docker/builder.go
- builder/docker/builder_test.go
- builder/kubernetes/builder.go
- builder/kubernetes/builder_test.go
- cmd/tsurud/migrate.go
- provision/docker/actions.go
- provision/docker/containers.go
- provision/docker/healthcheck.go
- provision/docker/provisioner.go
- provision/dockercommon/commands.go
- provision/env.go
- provision/kubernetes/builder_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/provision.go
- provision/swarm/healthcheck.go
- provision/swarm/healthcheck_test.go
This PR adds support to customize exposed ports for each process of an app on Kubernetes. Now we can expose more than one port for each process (both TCP and UDP), or config a process to avoid exposing any ports (like a worker).
This is a working implementation, although there are some limitations that I decided to leave to a future PR:
- healthcheck is set only on the first port of a process. Eventually we need to make this configurable
- the router port is attached to the first exposed port of the web process. We also need to discuss how to better handle this
- documentation is missing
Refs #2213
> Add support to multiple ports on Kubernetes

- provision/kubernetes/deploy_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
To support apps exposing multiple ports (#2249), the minimal deploy-agent version is 0.8.0
> provision/kubernetes: update deploy-agent version

- docs/managing/provisioners.rst
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/nodecontainer.go
- provision/kubernetes/nodecontainer_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/testing/reaction.go
They are generaly available in apps/v1 since kubernetes 1.9
> provision/kubernetes: move deployment and daemonset to v1 from v1beta1

- api/server.go
- api/team_token_test.go
Token info route was actually introduced in tsuru 1.7
> api: fix token info version

- integration/install_test.go
- provision/kubernetes/nodecontainer.go
This also required a change to allow setting hostPID: true in DaemonSets based on node-containers.
> integration: add node-container to ensure integration CA is installed

- integration/install_config_test.go
- provision/kubernetes/provider/provider.go
Even though container-engine knows the default values it doesnt use them unless the client explicitly sets them. :(
> provision/kubernetes: set default flags in kontainer-engine cluster

- api/context/context.go
- api/middleware.go
- api/service.go
- api/service_instance.go
- api/service_instance_test.go
This fixes the service proxy not forwarding a json body because it was being consumed during event creation.
> api: Preserve original request body after parsing arguments

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
When a process doesn't expose ports, only the headless service is created.
> provision/kubernetes: omit Service for processes with no exposed ports

- builder/kubernetes/suite_test.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/monitor.go
- provision/kubernetes/monitor_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/suite_test.go
With @guilhermebr 
This PR simplifies handling informers per cluster and also fixes informers becoming invalid when clusters are updated.
> provision/kubernetes: refactor informers per cluster

- provision/kubernetes/volume.go
- provision/kubernetes/volume_test.go
Since when we're deleting a volume we don't have any binds anymore it's
not possible to use them to find the PVC namespaces. Instead, we list
all PVCs from all namespaces including the volume name label and delete
them all.
> provision/kubernetes: ensure pvc is removed when deleting volume

- api/app.go
- app/app.go
- app/app_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
Implementation of issue: #2295
> Show related kubernetes-services in app-info

- app/actions.go
- app/app.go
- app/log.go
This commit also ensures that we retry collection creation before Insert
operations in the log database.
> app: no error on app create when log db unavailable

- app/log.go
- db/storage/storage.go
Also set timeouts explicitely instead of using deprecated
SetSocketTimeout function in database session.
> app,db: add flag to allow unsafe log write to mongodb

- builder/kubernetes/suite_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/node.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/suite_test.go
- provision/kubernetes/testing/reaction.go
We already had a node informer instance we just didn't use it everywhere yet. This PR changes this, now it's used everywhere we need to list nodes. This was made to address performance problems in /nodes calls which should be much faster now.
This change had an annoying impact on tests though. We must wait for a while after calls to Create()/Update() a node since these changes must be received by the informer loop and the in-memory cache updated. Some helper test functions were created to make waiting these changes easier.
> provision/kubernetes: use node informer for node listing

- api/tracker/tracker.go
- api/tracker/tracker_test.go
- applog/aggregator_test.go
- event/event.go
- event/event_test.go
- event/migrate/migrate_test.go
- event/webhook/webhook_test.go
- healer/suite_test.go
- provision/docker/healer/suite_test.go
- provision/provisiontest/fake_provisioner_test.go
- servicemanager/mock/servicemanager_mock.go
- types/tracker/tracker.go
- types/tracker/tracker_mock.go
This could make it easier to debug pending/frozen events.
> api/tracker,event: add instance information from tracker to created events

- api/quota.go
- api/quota_test.go
- permission/permitems.go
- permission/permlist.go
When I was working on issue #2239 , I found a security problem: Any user could update his/her own quota and no permission is required. This should be true about reading my own quota but not about changing it. So I did these steps:
* Added a user.read.quota permission
* Moved user/email context check from changeUserQuota to getUserQuota function
* Updated the tests
> read user quota permission + fix security problem

- iaas/dockermachine/iaas.go
- iaas/dockermachine/iaas_test.go
Fixes custom dockermachine driver options with env vars that need to be expanded.
> iaas/dockermachine: fix custom driver options with expanded env vars

- router/api/router.go
- router/api/router_test.go
Fixes not expanded env var on custom header value
> router/api: expand env var on custom header value

- api/app.go
- api/app_test.go
- api/handler_test.go
- api/middleware.go
- api/middleware_test.go
- api/quota_test.go
- api/server.go
- app/app.go
- app/app_test.go
- autoscale/autoscale.go
- autoscale/autoscale_test.go
- event/event.go
- event/event_test.go
- misc/check-events.sh
- misc/check-handlers.sh
- permission/permitems.go
- permission/permlist.go
- provision/docker/containers.go
- provision/docker/containers_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- router/api/routeriface.go
- router/rebuild/rebuild.go
- router/rebuild/task.go
- router/rebuild/task_test.go
- types/app/error.go
- types/app/lock.go
All handlers with side-effects are already protected by event locks, however we were still using the legacy app lock for some internal processes and had to maintain the app lock for consistency. This PR replaces all uses of the legacy app lock in internal processes for internal events. With this change there's no need for the app lock and it was removed.
> all: Remove legacy lock system in favor of internal events

- go.mod
- go.sum
- provision/kubernetes/monitor.go
- vendor/github.com/golang/groupcache/LICENSE
- vendor/github.com/golang/groupcache/lru/lru.go
- vendor/k8s.io/client-go/tools/leaderelection/OWNERS
- vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
- vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
- vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
- vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
- vendor/k8s.io/client-go/tools/record/OWNERS
- vendor/k8s.io/client-go/tools/record/doc.go
- vendor/k8s.io/client-go/tools/record/event.go
- vendor/k8s.io/client-go/tools/record/events_cache.go
- vendor/k8s.io/client-go/tools/record/fake.go
- vendor/modules.txt
This change will prevent multiple tsuru API instances from reacting to the same pod event generating duplicated work.
> provision/kubernetes: add leaderelection to cluster controller

- integration/install_test.go
Add option to disable master hosts acting as a tsuru pool. Some components on integration test, eg hostcert node-container, lead to an odd behavior on some scenarios, like when API server runs on masters. When docker is restart on those nodes by hostcert and kubernetes API runs on same hosts it may cause next test on flow to fail.
> integration: add option to disable pool for kubernetes masters

- provision/docker/containers.go
- provision/docker/provisioner_test.go
We should remove isolated containers (e.g containers created by `tsuru app-shell -i` and `tsuru app-run -i`) when they exit.
> AutoRemove isolated containers on exit

- api/info.go
- api/info_test.go
- api/server.go
- cmd/cmd.go
- cmd/cmd_test.go
Closes Issue #2257
tsuru --version now shows Server version as well as Client version. If it can't establish a connection to the server, it raises an error showing that the server is probably down.
> Returns server version on: /info route

- Makefile
- go.mod
- go.sum
- provision/kubernetes/monitor.go
- provision/kubernetes/testing/reaction.go
- provision/labels.go
- vendor/modules.txt
This also changes the election process to ensure we wait until election has stopped when shutting down the provisioner and a consistent handling of resource versions.
> provision/kubernetes: fix race in leader election with reactions

- app/app.go
- app/app_test.go
- provision/kubernetes/provisioner.go
- provision/provision.go
- router/galebv2/client/param_types.go
- router/galebv2/router.go
- router/galebv2/router_test.go
- types/router/router.go
This change is focused on the kubernetes provisioner, since healthcheck is handled by probes it makes sense to trust probes and only enable a simple tcp healthcheck on routers that support it.
> app,router,provision: tcp only healthcheck for provisioners handling HC

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
Not using useInRouter is unsafe and could lead to runtime issues. Let's not make this possible anymore on kubernetes.
> provision/kubernetes: always use continuous probe ignoring use-in-router

- builder/kubernetes/suite_test.go
- provision/cluster/cluster.go
- provision/cluster/cluster_test.go
- provision/kubernetes/monitor.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/suite_test.go
Only apply label filters to pod informer not the other informers. Also ensure the controller is stopped when a cluster is removed.
> Fixes to controller lifecycle and informer filters

- api/app.go
- api/app_test.go
- api/log_test.go
- app/app.go
- app/app_test.go
- app/deploy.go
- app/writer_test.go
- applog/aggregator.go
- applog/aggregator_test.go
- applog/service_test.go
The invert filters flag in log listing was being ignores in aggregate log service. This caused the logs messages shown to always repeat the deploy log instead of showing application specific log messages.
> Fixes last log lines shown after failed deploy

- api/app.go
- api/app_test.go
- app/app.go
- app/app_test.go
Now, if a user updates the app pool we must force its restart. That way, we make sure all units will be in the new pool. 
Also, the API now accepts the flag `noRestart` on the app update route, so the user can change the app plan without restarting it. The API returns a bad request error if a user tries to perform a pool update with the `noRestart` option.
> Allow app update with no restart

- api/app.go
- api/app_test.go
- api/deploy_test.go
- api/log_test.go
- api/logtracker_test.go
- app/app.go
- app/app_test.go
- app/deploy.go
- app/writer_test.go
- applog/aggregator.go
- applog/aggregator_test.go
- applog/dispatcher_test.go
- applog/memory.go
- applog/service_test.go
- applog/storage.go
- auth/token.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/monitor.go
- provision/provision.go
- storage/mongodb/applog.go
- storage/mongodb/applog_listener.go
- storage/storagetest/applog_suite.go
- types/app/log.go
Error messages during deploy were improved removed unnecessary information and duplicated lines. Also the log lines shown are only relative to the failed units. Here are some examples of the output before and after the change.
Before:
```
---- Updating units [web] ----
---> 0 of 1 new units created
---> 1 old units pending termination
---> myapp-web-848b95d8b6-j7ccj - Successfully assigned default/myapp-web-848b95d8b6-j7ccj to minikube [default-scheduler]
---> 1 of 1 new units created
---> 0 of 1 new units ready
---> myapp-web-848b95d8b6-j7ccj - Container image "192.168.50.1:5000/tsuru/app-myapp:v4" already present on machine [kubelet, minikube]
---> myapp-web-848b95d8b6-j7ccj - Created container myapp-web [kubelet, minikube]
---> myapp-web-848b95d8b6-j7ccj - Started container myapp-web …
```
> Improve error messages on failed deploy

- iaas/dockermachine/dockermachine.go
- iaas/dockermachine/dockermachine_test.go
- iaas/dockermachine/iaas.go
The log packgage inside docker/machine is a singleton, by updating it each time a new machine is created/destroyed we were at risk of a race condition updating the log.
Race example:
```
Write at 0x00c0000b41e0 by goroutine 88:
github.com/docker/machine/libmachine/log.(*FmtMachineLogger).SetOutWriter()
/Users/cezarsa/go/pkg/mod/github.com/cezarsa/machine@v0.7.1-0.20190219165632-cdcfd549f935/libmachine/log/fmt_machine_logger.go:31 +0x3a
github.com/tsuru/tsuru/iaas/dockermachine.NewDockerMachine()
/Users/cezarsa/go/pkg/mod/github.com/cezarsa/machine@v0.7.1-0.20190219165632-cdcfd549f935/libmachine/log/log.go:65 +0xcd0
github.com/tsuru/tsuru/iaas/dockermachine.(*S).TestNewDockerMachineRaceCheck.func1() …
```
> iaas/dockermachine: init logs only once

- api/middleware.go
- io/flushing_writer.go
- io/flushing_writer_test.go
Writing to a http.ResponseWriter after the handler has returned is not allowed but the consequences are not too drastic, usually you only end up with unexpected data in the socket. Calling `Flush()` however is a different story, it can cause an ugly panic as demonstrated in the test added here:
```
$ go test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x110056c]
goroutine 98 [running]:
bufio.(*Writer).Flush(0xc000196140, 0x0, 0x0)
/usr/local/Cellar/go/1.13/libexec/src/bufio/bufio.go:593 +0x5c
net/http.(*response).Flush(0xc0001bc000)
/usr/local/Cellar/go/1.13/libexec/src/net/http/server.go:1638 +0x35
github.com/tsuru/tsuru/io.(*FlushingWriter).Write(0xc00016e210, 0xc0000280de, 0x1, 0x1, 0x1, 0x0, 0x0) …
```
> io: prevent flushing and writing after on a closed writer

- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This is already valid, however after deploying an app with explicitely empty or nil ports further deploys would fail due to service not found. This PR also adds some extra tests to ensure the expected behavior happens when configuring an app with no ports.
> provision/kubernetes: fix errors when configuring empty ports for an app

- api/deploy.go
- app/deploy.go
- app/deploy_test.go
Before this change, some infos about the deploy such as Origin, Commit, and Message was always empty. This behavior was got since the bson.Raw cannot unmarshal the raw content into `DeployOptions` struct because of Token field there. This PR just drops the token of DeployOptions struct and logs the error in `eventToDeployData` function to make easy to find future problems.
> fix(app/deploy): show missing deploy data fields

- api/iaas.go
- api/iaas_test.go
- healer/healer_node.go
- healer/healer_node_test.go
- iaas/dockermachine/dockermachine.go
- iaas/dockermachine/iaas.go
- iaas/machine.go
- iaas/machine_test.go
- iaas/suite_test.go
- provision/docker/healer/suite_test.go
- provision/node/node.go
Twor major changes in this PR.
On the dockermachine IaaS implementation we now convert panics on `Close()` to regular errors, these panics are currently out of our control and may happen after an error in `DeleteMachine` calls.
Also on dockermachine implementation we convert cloudstack plugin information related to networks from a single string to a string slice due to changes in the plugin implementation.
The second major change is for the base IaaS implementation. We no longer ignore errors on destroy and instead return the error by default. A `force` flag was introduced to the iaas and to the related handler to allow us to ignore such errors and proceed with the removal from our internal storage.
> Fixes for IaaS destroy

- auth/oauth/oauth.go
- auth/oauth/oauth_test.go
This PR removes the need for validating the token against the authorization server. Now it's only verified locally by checking the expiry time boundary embed into oauth2 token.
NOTE: This PR also adds a new problem :roll_eyes: Even the user drops his session in the authorization server, his session in Tsuru API will not be deleted until the token expiration.
Closes #2355
> fix(auth/oauth2): validate token only using expiry time boundary

- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
There's a new config option which can be used to enable node registration again. The default is using it turned off because it's expected that kubelet itself will register the node in the cluster.
> provision/kubernetes: disable node creation in kubernetes by default

- provision/kubernetes/cluster.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
This PR adds a cluster config for disabling headless service creation (namely `<app>-<process>-units` svc). The config can be used to disable the creation for selected pools or for the whole cluster.
> provision/kubernetes: optionally disable headless service creation

- docs/reference/config.rst
- provision/docker/container/container.go
- provision/docker/container/container_test.go
- provision/docker/containers.go
This limit can help preventing a bad container from affecting the host with excessive forks like in a shell bomb.
> provision/docker: add pids limit config option

- provision/kubernetes/cluster.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
This can be configured per cluster or per pool in a cluster, previously these values were hardcoded at 100% and 0 for max surge and unavailable respectively.
> provision/kubernetes: Configurable max surge and unavailable in deploys

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
This allows us to use a reduced timeout values to identify errors faster
while also allowing for slow deployments with a large number of replicas
to be successful.
> provision/kubernetes: Reset deployment timeout when progress happens

- builder/kubernetes/builder.go
- provision/kubernetes/builder.go
- provision/kubernetes/builder_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/helpers.go
- provision/kubernetes/provisioner.go
- provision/provision.go
Now tsuru will show kubernetes events happening during image pull and inspect for image deploys. It will also show better error messages if the inspect pod failed to start. Event cancelation also propagates correctly to the deploy pod.
> provision/kubernetes: Improved errors and cancelation for image deploys

- provision/docker/actions.go
- provision/docker/actions_test.go
The bindsyncer goroutine is already responsible for adding and removing incorrect unit binds. Ignoring bind errors was already the default behavior in the kubernetes provisioner, this ensures both provisioner behaves equaly regarding unit binds.
> provision/docker: Ignore errors during bind unit when adding units

- router/rebuild/rebuild.go
- router/rebuild/task.go
Successful rebuild events are not really useful and create a lot of
noise in the events list.
> router/rebuild: Only save rebuild event on error

- app/version/service.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/node_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/labels.go
- types/app/version.go
With this change we go back to using `<app>-<process>` name for regular deployments and will ensure that regular rollouts will be used even after upgrading tsuru api.
> provision/kubernetes: Remove '-base' suffix for base deployments

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
The rollback operation on deployments only restores data in dep.Spec.Template. This change allows the rollback operation to restore the correct version labels atomically.
> provision/kubernetes: Use labels in pod template to find version 

- auth/oauth/oauth.go
- auth/oauth/oauth_test.go
- auth/oauth/token.go
- auth/oauth/token_test.go
By always reading the config we can change oauth configs without restarting tsuru.
> auth/oauth: Make types private and always read urls from config

- provision/kubernetes/cluster.go
- provision/kubernetes/cluster_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/node.go
- provision/kubernetes/node_test.go
- provision/kubernetes/nodecontainer.go
- provision/kubernetes/nodecontainer_test.go
- provision/kubernetes/provisioner.go
This PR adds a new `single-pool` option to cluster that allows using the entire cluster as a single Tsuru pool
> provision/kubernetes: add option to use entire cluster as a single pool

- docs/installing/planb-router.rst
This PR adds more information about how to configure planb on systemd based hosts.
This update is necessary because FPM (used at `https://github.com/tsuru/planb/blob/master/misc/fpm_recipe.rb`) doesn't add as a parameter an environment variable.
Changing the FPM configuration doesn't have the expected result. When FPM script has your `pleaserun.input` altered to include `$PLANB_OPTS`, the result is escaped on systemd file.
```
pleaserun.input ["/usr/bin/planb", "$PLANB_OPTS"]
```
Generates at `/etc/systemd/system/planb.service`:
```
ExecStart=/usr/bin/planb "\$PLANB_OPTS"
```
Thus, as it is not possible to generate a `/etc /systemd/system/planb.service` file where`ExecStart` uses the `$PLANB_OPTS` environment variable, the documentation has been updated to inform that the user must make …
> docs: add more information about planb configuration

- api/logtracker_test.go
- api/server.go
- api/suite_test.go
- app/app.go
- app/service.go
- app/suite_test.go
- applog/dispatcher.go
- applog/memory.go
- applog/provisioner_wrapper.go
- applog/provisioner_wrapper_test.go
- applog/service.go
- provision/kubernetes/cluster.go
- provision/kubernetes/logs.go
- provision/kubernetes/logs_test.go
- provision/kubernetes/monitor.go
- provision/kubernetes/monitor_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/suite_test.go
- provision/kubernetes/testing/reaction.go
- provision/pool/pool.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- service/suite_test.go
- servicemanager/servicemanager.go
- types/app/app.go
- types/app/app_mock.go
- types/app/log_mock.go
- types/app/version.go
- types/app/version_mock.go
This MR is an architectural change using kubernetes provisioner, we intend to maintain Tsuru as a globally control-plane application, we are assigning the responsibility to store logs on kubelet engine, then allowing Tsuru to maintain many k8s clusters without bottleneck.
> Stream logs directly from kubernetes api-server

- api/pool_test.go
- provision/pool/constraint.go
This PR fixes a condition on pool constraint which compares multiple teams against pool constraints and skip at first false evaluation for a team instead trying remaining teams comparison on a list.
> Fix pool list for users on multiple teams

- provision/cluster/metrics.go
- provision/cluster/metrics_test.go
in a multi-cluster environment we need to wisely choose the right cluster before using metrics in singleton grafana instance.
This MR add new metric named `tsuru_cluster_info` that will be useful to use as a grafana variable.
> provision/cluster: add metrics for cluster info

- api/permission.go
- api/permission_test.go
- api/server.go
- api/suite_test.go
- auth/group.go
- auth/oauth/oauth.go
- auth/oauth/oauth_test.go
- auth/suite_test.go
- auth/user.go
- auth/user_test.go
- cmd/tsurud/token.go
- cmd/tsurud/token_test.go
- docs/reference/api.yaml
- permission/permission.go
- provision/docker/handlers_test.go
- servicemanager/mock/servicemanager_mock.go
- servicemanager/servicemanager.go
- set/set.go
- storage/driver.go
- storage/mongodb/auth_group.go
- storage/mongodb/auth_group_test.go
- storage/mongodb/mongodb.go
- storage/storagetest/auth_group_suite.go
- types/auth/group.go
- types/auth/group_mock.go
- types/auth/user.go
This chance makes it possible to assign roles to groups. Groups are entities that the auth provider dynamically set on each user and which tsuru has no control over.
Example of a possible use:
```
tsuru role-assign team-member group:mygroup teamX
```
This means that every user belonging to group `mygroup` (according to information by the auth provider) will now have the role `team-member` with context value of `teamX`.
> Read groups from oauth provider and allow roles to groups

- app/app_test.go
- app/image/gc/gc_test.go
- app/image/image_test.go
- app/version/service_test.go
- storage/mongodb/app_version.go
- storage/storagetest/app_version_suite.go
It means that we won't remove the appVersion anymore for these reasons:
* When user removes a app and create again, could generate inconsistency in nodes by a previous docker image cached, ie myapp:v1.
* ensure that image could safety used by `IfNotPresent` image policy, because we won't reuse previous version number of any app.
> Avoid to remove appVersion document

- README.md
While following the instructions to install tsuru-client from source I found that the `git clone` command was missing the protocol. The command returned an error: `fatal: repository 'github.com/tsuru/tsuru-client' does not exist`. So I added the protocol to the command.
>  README: fix git clone instructions

- cmd/open.go
In WSL, the command `powershell.exe` it's being called to open GUI. The `url` parameter must be wrapped with quotes to prevent keyword use.
```
No linha:1 caractere:93
... .globoi.com/authorize?client_id=z4kjNVz4XJMUwc2YjgBCuw%3D%3D&redirect ...
~
O caráter de E comercial (&) não é permitido. O operador & está reservado para uso futuro; coloque um E comercial entre aspas duplas ("&") para
transmiti-lo como parte de uma cadeia de caracteres.
No linha:1 caractere:129
... NVz4XJMUwc2YjgBCuw%3D%3D&redirect_uri=http://localhost:37621&response ...
~
O caráter de E comercial (&) não é permitido. O operador & está reservado para uso futuro; coloque um E comercial entre aspas duplas ("&") para
transmiti-lo como parte de uma cadeia de caracteres.
+ CategoryInfo          : ParserError: (:) [], …
```
> bugfix: Wrapping url parameter with quotes to prevent keyword use

- db/storage.go
- event/event.go
- event/event_test.go
To take less time searching events, it created 3 new indexes, besides that, it is dropped the use of extraTargets in the query
> events: optimize the query for deploy events

- api/server.go
- api/service.go
- api/service_test.go
- app/app.go
- app/app_test.go
- app/bind/binder.go
- docs/reference/api.yaml
- provision/pool/pool.go
- provision/provisiontest/fake_provisioner.go
- service/endpoint.go
- service/endpoint_test.go
- service/service.go
- service/service_instance.go
- service/service_instance_test.go
- servicemanager/mock/servicemanager_mock.go
- servicemanager/servicemanager.go
- storage/driver.go
- storage/mongodb/mongodb.go
- storage/mongodb/pool.go
- storage/mongodb/pool_test.go
- storage/storagetest/pool_suite.go
- types/provision/pool.go
- types/provision/pool_mock.go
Some Tsuru Services likely run on the same region/zone/cluster/nodes of Tsuru Apps, e.g. some database service to reduce the network latency and bandwidth. Before this PR, we'd to create several Tsuru Services for each cluster/pool (e.g `db-service-pool-aws-east`, `db-service-pool-south-america`, etc). That demands a lot of operational work.
This PR creates a new sort of Tsuru Services, the multi-cluster ones. They're like regular Tsuru Services but (their service instances) should run into a valid Tsuru Pool. All subsequent requests to Service API the Tsuru is going to include HTTP headers to identify the pool and cluster where the Service Instance is running on.
HTTP headers sent by Tsuru API to Service API:
* `X-Tsuru-Pool-Name`: the pool name;
* `X-Tsuru-Pool-Provisioner`: the …
> feat(service): support for multi-cluster services

- api/deploy_test.go
- app/app.go
- app/app_test.go
- app/deploy.go
- db/storage.go
- event/event.go
- event/event_test.go
- event/eventlist_test.go
- event/eventtest/checker.go
There is no benefit in marking events as removed. This code removes
everything related to marking events as removed as well as filtering by
removed events.
> Events are no longer removable

- api/volume.go
- api/volume_test.go
- provision/pool/pool.go
- provision/pool/pool_test.go
- volume/volume.go
* Allow creation of volumes by default so it doesn't break the creation of volumes pipeline.
* To a specific volume-plan from being created one needs to add the constraint with the blacklist flag.
* Allow the usage of regex on poolExpr when setting the volume-plan constraint
> Add volume constraint

- api/pool_test.go
- go.mod
- provision/kubernetes/cluster.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/pool/pool.go
- provision/pool/pool_test.go
feat: add nodeAffinity according to pool label to pods when deploying in kubernetes
feat: use pool nodeSelector if cluster does not specify a node selector
change: don't use any nodeSelector if one is not found in cluster or pool
> Add labels to pools

- api/router/router.go
- api/router/router_test.go
PATCH method is not currently supported, this leads to services APIs not being able to use it through the services proxy.
> refactor: support PATCH method on router.AddAll

- docs/reference/config.rst
- docs/using/tsuru.yaml.rst
- provision/docker/healthcheck.go
- provision/docker/healthcheck_test.go
- provision/dockercommon/deploy.go
- provision/kubernetes/deploy.go
- requirements.txt
- types/provision/provision.go
This PR adds the field `deploy_timeout_seconds` to the health check yaml configuration. I'm open for suggestions on a better name for this field.
> Allow configurable timeout for healthcheck passing during deploy

- api/app.go
- api/app_test.go
- app/app.go
- app/bind/binder.go
- docs/reference/api.yaml
- types/api/env.go
EnvVars API is not really terraform friendly, and we have to create a diff locally and remove / update with multiple requests.
This PR lets we push update all variables with a single requests, pruning unneeded variables if requested. The pruning only happens to variables managed by the same service ie. `terraform`, `tsuru-client`, and so on.
What is missing from this PR is a change to the database model, making all variables public, except those marked as `private`.
> refactor: improve env-vars API for easier integration with terraform

- app/app.go
- app/app_test.go
Today we cannot run app shell command against an app that doesn't have `bash`, such as Alpine-based platforms. This PR tries to find `bash` executable before executing it or calls `dash` otherwise.
> feat(app/shell): fallback to dash when bash is not found

- api/app_test.go
- api/node_test.go
- app/app.go
- app/app_test.go
- app/version/service_test.go
- app/version/version.go
- autoscale/autoscale_test.go
- provision/kubernetes/deploy_simple_test.go
- provision/provisiontest/fake_provisioner.go
- provision/provisiontest/fake_provisioner_test.go
- provision/servicecommon/state.go
- storage/mongodb/app_version_test.go
- storage/storagetest/app_version_suite.go
- types/app/version.go
This PR reintroduces a feature removed in [#2539](https://github.com/tsuru/tsuru/pull/2539), tsuru-api persists the last state of the process-version pair inside its storage provider and tries to restore it when attempting to start a previously stopped deployment.
TLDR: if `tsuru app stop -a <appname> --process <processname> --version <versionnumber>` had 3 units running, a `tsuru app start -a <appname> --process <processname> --version <versionnumber>` will restore it with 3 units
> Save and retrieve unit status from storage

- Makefile
- docker-compose.yml
This PR fix the issue #2582 and adds a mongo version supported by tsuru on docker compose.
> Fixing issue 2582 and adding mongo version

- api/build.go
- api/deploy.go
- api/deploy_test.go
- app/deploy.go
- builder/builder.go
- builder/docker/builder.go
- builder/kubernetes/build_v2.go
- builder/kubernetes/build_v2_test.go
- builder/kubernetes/builder.go
- builder/kubernetes/builder_test.go
- docs/reference/api.yaml
- permission/permitems.go
- permission/permlist.go
- router/api/routeriface.go
As of https://github.com/tsuru/deploy-agent/commit/701d1f514f7a08da5f5be87f6c54df98d095a099, Deploy Agent v2 supports deploy w/ Dockerfile. Following that changes, this PR implements the support deploy w/ Dockerfile from Tsuru API as wel.
> feat(build/k8s): support deploy with Dockerfile

- api/app.go
- api/app_test.go
- types/api/env.go
This PR prevents user adding env var that aren't UNIX compliant onto app.
> fix(api/app): preventing to add non-UNIX env var names

- docs/reference/api.yaml
updating openAPI spec
Add missing properties to `App`:
- unitMetrics (array of unitMetrics)
- autoscaleRecommendation (array of RecommendedResources)
- error (string)
- quota (Quota)
- serviceInstanceBinds (array of objects)
> update AppGet openSpecAPI

- api/job.go
- permission/permitems.go
- permission/permlist.go
instead of the misleading job.run event which is used on another scenario
> refactor: add job trigger event 

- CONTRIBUTORS
- builder/kubernetes/build_v2.go
- go.mod
- go.sum
- provision/kubernetes/cluster.go
- provision/pool/pool.go
- provision/pool/pool_test.go
The `github.com/ghodss/yaml` package is no longer being actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, while `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. You can see the changes between the two versions here: [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), which mostly consists of bug fixes.
> chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

- api/auth.go
- api/auth_test.go
- permission/permitems.go
- permission/permlist.go
APIkey is two-edged sword, this feature allow users to fast and simple configure CI and allow to authenticate on tsuru when identity provider is down, in other hand it is a token without expiration, causing a insecure access.
to solve this problem, we could disable apikey for major users, via role we could add permission to only admins use that in case of downtime of identity provider.
users can continue using team tokens that is a better manner to auth on CI
> Extract apikey permission to allow to disable apikey generation for some users

- provision/provision.go
- provision/provision_test.go
Autoscales uses deployment to check for a few informations, so allowing scaling a process to 0 currently makes you unable to change/delete that autoscale.
> revert: min units 0

- CONTRIBUTORS
- docs/conf.py
- docs/installing/installing-minikube.rst
- docs/installing/installing-tsuru-components.rst
- docs/releases/tsr/0.11.0.rst
- docs/releases/tsurud/0.13.0.rst
- docs/services/build.rst
- requirements.txt
When following the doc **Installing Tsuru in a local Kubernetes cluster with Helm** there is an extra `s` in [Configuring Tsuru](https://docs.tsuru.io/main/installing/installing-minikube.html#configuring-tsuru) that will make `tsuru cli` not find the API.
In order to generate the docs for validation I had to do the following:
1. Create a virtual environment with Python 2.7
2. Pin a couple of Python's dependencies so Sphinx can start properly.
3. Move `releases RELEASES` to the try block for running locally without problems.
4. Fix some old reference targets in the docs
> docs: Fix typo in Installing Tsuru in a local Kubernetes

- docs/reference/api.yaml
- provision/kubernetes/autoscale.go
- provision/kubernetes/autoscale_test.go
- provision/provision.go
- provision/provision_test.go
Adds support to KEDA Prometheus Autoscale
Uses template to define default Prometheus URL
- Template config should be defined on `kubernetes:keda:prometheus-address-template`
> KEDA Prometheus Autoscale

- api/server.go
- api/service_instance.go
- api/service_instance_test.go
- service/endpoint.go
The Tsuru has a way to proxy requests to a backend of service instance, nowadays is:
```
/services/<SERVICE>/proxy/<INSTANCE>?callback=%2Fresources%2F<INSTANCE>%2F<CUSTOM_PATH>
```
why evolve to a new model?
* repeat <INSTANCE> on callback querystring is a little redundant
* user could escape to a instance that does not have permission, i. e: `/services/<SERVICE>/proxy/instance-a?callback=%2Fresources%2Finstance-b%2Finfo`
* simplify clients codebase.
proposal:
new proxy API with same permission model, but with a syntax sugar:
```
/1.20/services/<SERVICE>/resources/<INSTANCE>/<CUSTOM_PATH>
```
this model ensure easy way to interoperate trough tsuru api and directly access.
ex:
* trough tsuru api: http://mytsuru.com/1.20/services/myservice/resources/instance/info
* direct access: …
> service instance proxy V2

- api/app.go
- api/app_test.go
- api/job.go
- api/job_test.go
- api/scale.go
- api/scale_test.go
- app/app.go
- app/app_test.go
- job/job.go
- provision/kubernetes/autoscale.go
- provision/kubernetes/autoscale_test.go
- provision/kubernetes/job.go
- provision/kubernetes/metrics.go
- provision/kubernetes/metrics_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/provision.go
- provision/provision_test.go
- provision/provisiontest/fake_provisioner.go
- provision/provisiontest/fake_provisioner_test.go
- service/endpoint_test.go
- storage/mongodb/plan.go
- types/app/app.go
- types/app/plan.go
- types/job/job.go
- types/provision/autoscale.go
- types/provision/unit.go
types standard provides more reusable pattern and simplify dependecy of structs that are wide used.
the app package is the major one that is no migrated.
working to standardize the project.
> Migrate app package to types standard - part 1

- api/app_test.go
- api/event_test.go
- api/job_test.go
- api/middleware.go
- api/pool_test.go
- api/server.go
- api/suite_test.go
- api/webhook_test.go
- go.mod
- go.sum
- service/endpoint.go
The replace directives for the packages `github.com/ajg/form` and `github.com/samalba/dockerclient` are both redundant.
We can require github.com/cezarsa/form directly and bypass the replace.
gofmt -w -r '"github.com/ajg/form" -> "github.com/cezarsa/form"' .
The second replaced package does not seem to be in use according to `go list -m all`.
There is a hidden bonus that `go install github.com/tsuru/tsuru/cmd/tsurud@latest`
is now a thing.
For: tsuru/tsuru-client#226
> Remove redundant replace directives

- Makefile
- docker-compose.yml
- router/api/router.go
1. Removed deprecated `version` for `docker-compose.yml`
2. Local environment  on the Mac M series should start properly using `make local-mac-mseries`
3. Fixed bug that prevents Tsuru API to start when there's a Router without TLS support and debug flag is active.
> fix: Improving local development experience

- api/permission.go
- api/service_instance.go
- service/service_instance.go
- service/service_instance_test.go
When I started developing an improvement to the "tsuru service list" command, I noticed that the GET request made by the tsuru-client makes a request to the endpoint '/1.0/services/instances' and not to '/1.0/services/', so I made this endpoint also able to use tags to filter service instances.
> feat: Add filtering by tags in service instance list

- app/version/customdata.go
- app/version/customdata_test.go
- builder/kubernetes/build.go
- builder/kubernetes/build_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- router/rebuild/rebuild_test.go
- types/provision/provision.go
- types/router/router.go
The ideia is to introduce a new format to tsuru.yaml. It might deprecate Procfile usage.
```yaml
processes:
- name: web
command: python app.py
healthcheck:
path: /
scheme: http
- name: web-secondary
command: python app2.py
healthcheck:
path: /
scheme: http
```
> Feat - Multiple App Healthchecks

- app/app.go
- app/image/gc/gc.go
- app/image/gc/gc_test.go
- app/platform_test.go
- cmd/cmd_test.go
- go.mod
- go.sum
- log/file_logger.go
- registry/registry.go
- registry/registry_test.go
- registry/testing/server.go
- using docker config style and dropping old registry credential config for all clusters
- allowing using separated credentials for different clusters instead single auth basic credential
- fix on RemoveAppImages when app is removed
- add support for docker registry realm style authentication
> registry: tweaks for image cleanup

- api/app.go
- app/actions.go
- app/app.go
- provision/pool/constraint.go
- provision/pool/pool.go
- provision/pool/pool_test.go
The tsuru API currently does not validate whether the certificate issuer exists in the cluster when managing apps.
Proposed Solution:
This MR introduces validations steps to check if the certificate issuer already exists in the cluster for the app before execute any action and if the pool's app have some constraints for certificates issuers.
The validation leverages the [constraints API](https://github.com/tsuru/tsuru/blob/main/provision/pool/constraint.go) to simplify the implementation and ensure consistency with existing cluster policies.
Key Changes:
- Added issuer validation during app creation and updates;
- Integrated with the constraints API for efficient checks;
- Improved error handling with clear feedback for missing issuers;
ToDo:
1. API - Make the endpoint …
> Fix: Cert issuer validation for apps
