- .travis.yml
And add `echo` and `sleep` to `while` loops for retrying.
> .travis.yml: wait for Redis port 6379

- cmd/client.go
- cmd/client_test.go
- cmd/cmd.go
Verbosity: 1 => print HTTP requests; 2 => print HTTP requests/responses
Fixes #959 
E.g.:
```
❯ tsuru -v 2 app-info -a someapp
*************************** <Request uri="/apps/someapp"> **********************************
GET /apps/someapp HTTP/1.1
Host: tsuru.corp.surveymonkey.com:8080
Connection: close
Authorization: bearer 6efcfbba38127d5f3c9a7121a8833e76ccb7f5cc
*************************** </Request uri="/apps/someapp"> **********************************
*************************** <Response uri="/apps/someapp"> **********************************
HTTP/1.1 404 Not Found
Connection: close
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8
Date: Sat, 27 Dec 2014 00:50:34 GMT
Supported-Crane: 0.6.0
Supported-Tsuru: 0.14.0
Supported-Tsuru-Admin: 0.8.1
17
App someapp not …
```
> Add -v global flag for verbosity

- api/server.go
in case folks don't know what kind of database is used.
> Specify "mongodb" in log message

- .gitignore
- Makefile
Similar change to https://github.com/tsuru/gandalf/pull/176.
* binaries
- tsr
* run
* run-tsr-api
* run-tsr-token
> Add more Makefile targets

- .travis.yml
My attempt at making Travis not error out on my tsuru fork.
> .travis.yml: Generalize sed so works with forks

- cmd/shell.go
- cmd/shell_test.go
> cmd: improve app-shell error output 

- docs/advanced_topics/metrics.rst
- docs/contributing/coding-style.rst
- docs/contributing/index.rst
- docs/installing/adding-nodes.rst
Improved message for failing tests and fixed some typos.
> Improve documentation

- app/app.go
@fsouza is this what you suggested?
> app-list returns JSON error while app removal is running in background #1119

- app/app_test.go
add missing test from issue #1119
> app: add missing test for MarshalJSON

- db/storage/storage.go
- db/storage_test.go
> db/storage: improve error message for mongodb connection handling

- app/app.go
- app/app_test.go
- provision/docker/provisioner.go
- provision/docker/provisioner_test.go
- provision/provisiontest/fake_provisioner.go
guys, could you please review this PR? if there is anything missing please say me. I'm just getting used to tsuru's codebase yet.
> app: support removing all units from the application #1111

- provision/docker/scheduler.go
- provision/docker/scheduler_test.go
> tsuru-admin: docker-pool-teams-add returns bad error when pool doesn't exist

- api/app.go
- api/app_test.go
- api/suite_test.go
- app/app.go
- app/app_test.go
- app/deploy.go
- provision/docker/image.go
- repository/gandalf/gandalf.go
> cmd/tsuru: add filters in app-list 

- provision/docker/actions.go
- provision/docker/actions_test.go
> Enhancement in tsuru unit names (#1160)

- docs/installing/gandalf.rst
Fixed minor spelling mistake in documentation.
> Fixed minor spelling correction in gandalf doc

- docs/installing/gandalf.rst
- docs/reference/config.rst
While reading through the documentation I noticed some very small typos and grammatical errors, so I thought I might as well raise a PR to correct them. None are a big deal, just pedantic corrections!
> Very small grammatical corrections

- docs/contributing/index.rst
- docs/managing/using-pools.rst
- docs/using/go.rst
- docs/using/logging.rst
- docs/using/recovery.rst
- docs/using/ruby.rst
- docs/using/unit-states.rst
Similar to https://github.com/tsuru/tsuru/pull/1184 - just a few small changes to typos and to clarify the language in a few places.
> Fixed a few typos and clarified a few confusing parts of the docs

- docs/installing/hipache-router.rst
See https://github.com/hipache/hipache/blob/master/lib/cache.js#L14
> Remove deprectated redis driver options

- cmd/target.go
This patch solve the issue #1297
> Creating .tsuru directory before write a target

- provision/docker/actions.go
- provision/docker/actions_test.go
> provision.docker: do not add route to container when HostPort is zero

- docs/installing/adding-nodes.rst
Improve the docs when adding unmanaged node
> Complete docs for add unmanaged node with pool at the setttings

- docs/advanced_topics/metrics.rst
Fixes Elasticsearch installation URL and updates Logstash configuration for the latest version.
> docs: update metrics page

- app/app.go
- app/app_test.go
- service/bind_test.go
The env TSURU_SERVICES in many cases it was duplicated service instances in json.
> app: Fixes duplicated service instance at bind

- docs/installing/api.rst
Without this, docker nodes are stuck in "pending"
> Added missing docker:bs section in tsuru.conf

- iaas/ec2/task.go
When starting  a node, a few times I get a 503 from the EC2 api,
this would stop the instance start.
Now It retries the api call before a hard timeout.
> Ignoring intermittent errors on EC2 api

- validation/validation_test.go
Proving the issue https://github.com/tsuru/tsuru/issues/1442 isn't a email validation's problem by improving email validation's tests.
> validation: testing prefix+email.com case on ValidateEmail

- docs/using/docker-image.rst
- docs/using/index.rst
* This doc describes how to deploy a docker image using a private and insecure registry.
* On this example I used the static platform, by be a light platform.
> Documentation about how to deploy a docker image

- docs/reference/config.rst
Add missing documentation for sharedfs setup
> add documentation for SharedFS configuration. resolve #985

- docs/conf.py
- docs/theme/sphinx_rtd_theme/theme.conf
- docs/theme/sphinx_rtd_theme/versions.html
This PR extends sphinx_rtd_theme to show versions in docs sidebar.
> extend docs theme to show versions

- iaas/digitalocean/iaas.go
- iaas/digitalocean/iaas_test.go
> shutdown droplet before remove

- docker-compose.yml
- docs/contributing/compose.rst
- etc/tsuru-compose.conf
This PR add gandalf container to docker-compose.
depends on https://github.com/tsuru/gandalf/pull/207
> compose: add gandalf

- api/iaas.go
- api/iaas_test.go
this was ment to solve tsuru/tsuru#1539
> Iaas template update (WIP)

- provision/docker/provisioner.go
- provision/docker/provisioner_test.go
> image deploy: fix message of no nodes in app pool

- docs/using/tsuru.yaml.rst
> Add docs about the router health check

- api/pool.go
- api/pool_test.go
This blocks the user from removing a pool that still
contains apps. Fixes tsuru/tsuru#1575
> api: Blocks removal of pools with apps

- api/service_instance.go
- api/service_instance_test.go
> api: print remove service instance messages in different lines

- api/app.go
- api/app_test.go
- app/app.go
- app/app_test.go
- permission/permitems.go
- permission/permlist.go
> adds support for image-reset on next deploy by using app-update

- api/permission.go
- api/permission_test.go
- api/server.go
- auth/user.go
- auth/user_test.go
- permission/permission.go
- permission/role.go
- permission/role_test.go
> role-update command

- api/app.go
- api/app_test.go
- api/suite_test.go
- app/app.go
- app/app_test.go
- app/suite_test.go
- permission/permitems.go
- permission/permlist.go
fixes #1591 
After merge of this and #1590 It'll be needed to do some adaptations on master.
> app-update platform

- api/app.go
- api/app_test.go
- api/deploy.go
- api/deploy_test.go
- app/deploy.go
- app/deploy_test.go
> App create without platform

- api/auth.go
- api/auth_test.go
> api: Fixed user list. Added a message for when the context is wrong.

- api/app_test.go
- api/service.go
- api/service_instance_test.go
- api/service_test.go
- app/app_test.go
- app/bind_test.go
- provision/docker/suite_test.go
- provision/swarm/suite_test.go
- service/actions_test.go
- service/bind_test.go
- service/service.go
- service/service_instance_test.go
- service/service_test.go
With this PR we start validating the service name. I'm skipping the name validation on the update until we decide if we are going to support updating the service name
> api,service: validates service name

- event/block.go
- event/block_test.go
With this commit if the users block e.g "app.update"
any event that starts with "app.update" will be blocked,
e.g, "app.update.add.unit"
> event: blocks children events when parent is blocked

- integration/install_config_test.go
- integration/install_test.go
This is possible due to https://github.com/tsuru/tsuru-client/pull/44
> integration: sets api version on installer config

- auth/team.go
- auth/team_test.go
> Fix issue #1613

- Makefile
- integration/install_test.go
This PR adds some service logic to our integration testing.
> integration: adds service create/bind/unbind 

- provision/docker/containers.go
- provision/docker/provisioner_test.go
> provision/docker: uses app environment variables on isolated run

- api/app.go
- api/app_test.go
- api/auth_test.go
- api/deploy_test.go
- api/event_test.go
- api/platform.go
- api/platform_test.go
- api/service_instance_test.go
- api/suite_test.go
- app/platform.go
- app/platform_test.go
- app/suite_test.go
- db/storage.go
- db/storage_test.go
- storage/driver.go
- storage/mongodb/mongodb.go
- storage/mongodb/platform.go
- storage/mongodb/platform_test.go
- storage/mongodb/suite_test.go
- storage/mongodb/team.go
- storage/mongodb/team_test.go
- types/app/platform.go
Create a `PlatformService` type to encapsulate access to platform storage.
> Platform service

- api/service_instance.go
- api/service_instance_test.go
- permission/permitems.go
- permission/permlist.go
- service/service_instance_test.go
> Service instance update team owner

- docs/faq.rst
- docs/managing/clusters.rst
- docs/managing/index.rst
- docs/managing/provisioners.rst
> docs: add docs about clusters and provisioners

- router/galeb/client/galeb.go
- router/galeb/client/galeb_test.go
This prevents us from making unnecessary pool update requests, which are much more costly.
> router/galeb: prevent updating pool if healthcheck has not changed

- api/app_test.go
- api/auth_test.go
- api/deploy_test.go
- api/event_test.go
- api/handler_test.go
- api/log_test.go
- api/platform_test.go
- api/quota_test.go
- api/service_instance_test.go
- api/service_test.go
- api/suite_test.go
- app/app_test.go
- app/bind_test.go
- provision/docker/suite_test.go
- provision/pool/pool_test.go
- service/actions_test.go
- service/bind_test.go
- service/service.go
- service/service_instance.go
- service/service_instance_test.go
- service/service_test.go
- service/suite_test.go
- service/sync_test.go
Adds team owner validation when creating or updating services and service instances.
Fixes #1680
> Service team owner validation

- integration/install_config_test.go
> integration: add a node for platform building when there's no node available

- api/service_instance.go
- api/service_instance_test.go
> api: handle bounded apps error

- api/service.go
- api/service_test.go
`service update` command was ignoring team field
> api: add team field to service update

- service/bind_test.go
- service/service_instance.go
- service/sync.go
- service/sync_test.go
> service: fix binsyncer to handle instance bound to multiple apps

- builder/docker/actions.go
- builder/docker/actions_test.go
- builder/docker/builder.go
- builder/docker/docker.go
- provision/dockercommon/docker.go
- provision/dockercommon/docker_test.go
> Revert "builder: add uploadToContainer action"

- integration/install_test.go
cluster-remove will ask for confirmation to proceed. This test has been updated to account for the change.
https://github.com/tsuru/tsuru/issues/1777
> client: Update install test to account for cluster-remove confirmation #1777

- .gitignore
- docs/conf.py
- docs/index.rst
- docs/plugins/index.rst
A plugins section where contributors and maintainers can list their tsuru plugins.
Refs.: #1679
> Plugins Docs

- Makefile
- api/iaas.go
- api/node.go
- api/node_test.go
- autoscale/autoscale.go
- autoscale/memory.go
- healer/healer_node.go
- healer/healer_node_test.go
- iaas/machine.go
- iaas/machine_test.go
- integration/cluster_manager.go
- integration/gce.go
- integration/install_config_test.go
- integration/install_test.go
- integration/minikube.go
- integration/suite_test.go
- integration/swarm.go
- integration/unit_test.go
- provision/docker/provisioner.go
- provision/kubernetes/node.go
- provision/kubernetes/node_test.go
- provision/labels.go
- provision/labels_test.go
- provision/node.go
- provision/provision.go
- provision/provision_test.go
- provision/provisiontest/fake_provisioner.go
- provision/swarm/node.go
- provision/swarm/node_test.go
Also add node healing to the integration tests.
> use node labels without prefix when calling iaas

- provision/swarm/provisioner.go
It may that a container originating from a task starts before docker updates the task status with the container id.
> provision/swarm: wait for docker to update task status adding containerid

- README.md
Also updated the Travis status icon to the SVG version ✨
> Fix spelling/grammar in README.md

- api/app.go
- api/app_test.go
- app/actions.go
- app/app.go
- app/app_test.go
- provision/provisiontest/fake_provisioner.go
> api,app: allow changing app pool to different provisioner

- provision/swarm/provisioner.go
UpdateStatus might be nil right after the update has started and only
changes afterwards.
> provision/swarm: handle UpdateStatus nil on DeployService

- router/api/generator/combinations.go
- router/api/router.go
- router/api/router_test.go
- router/api/routeriface.go
- router/router.go
- router/router_test.go
- router/routertest/generic_suite.go
- router/suite_test.go
Also implement new interfaces in api router
> router: add new interfaces for info and status routers

- api/router.go
- api/router_test.go
- app/app.go
- provision/pool/pool.go
- provision/pool/pool_test.go
Add constraint validation when adding or updating routers to an app. Fixes #1856
> App router validation

- builder/docker/builder.go
- builder/docker/builder_test.go
- provision/dockercommon/docker.go
- provision/dockercommon/docker_test.go
- provision/provision.go
Add healthcheck data from `tsuru.yaml` when deploying from an image
> Image deploy healthcheck

- api/app_test.go
- api/pool_test.go
- api/router_test.go
- app/app_test.go
- provision/pool/constraint.go
- provision/pool/constraint_test.go
- provision/pool/migrate.go
- provision/pool/migrate_test.go
- provision/pool/pool.go
- provision/pool/pool_test.go
This PR also includes a refactor of constraints fields (now called types).
> provision/pool: validates constraint type on append

- app/deploy.go
- app/deploy_test.go
- builder/builder.go
- builder/builder_test.go
- builder/docker/builder.go
- builder/docker/builder_test.go
- builder/fake/builder.go
- builder/fake/builder_test.go
- provision/docker/provisioner_test.go
- provision/dockercommon/docker.go
- provision/dockercommon/docker_test.go
- provision/swarm/provisioner_test.go
This PR prevents deploy of image created by app-build to set updatePlatform flag to True
> app,builder: makes buildedImage deploy don't set updatePlatform

- docs/reference/router_api.yaml
I've looked for something similar in the repo but didn't found anything. Please point me if there is any api spec documented, besides generating code with impl. 
Easy to implement new routers in other languanges generating with swagger.
We should also have one for 'repo-manager' api and 'service' api. 
Right now its hard to start integrating because you need to look into examples/original code.
> Openapi router api specification, 

- app/app.go
- router/rebuild/rebuild.go
- router/rebuild/rebuild_test.go
- router/routertest/router.go
> app,router/rebuild: sets router healthcheck on routes rebuild

- docs/reference/service_api.yaml
Continues the work started by #1892
> docs: adds openapi reference for service api

- Gopkg.lock
- vendor/github.com/globalsign/mgo/bson/bson.go
- vendor/github.com/globalsign/mgo/bson/compatibility.go
- vendor/github.com/globalsign/mgo/changestreams.go
- vendor/github.com/globalsign/mgo/cluster.go
- vendor/github.com/globalsign/mgo/session.go
- vendor/github.com/globalsign/mgo/socket.go
This version includes important fixes in particular a fix for
globalsign/mgo#103
> vendor: update globalsign/mgo version

- provision/kubernetes/deploy.go
Using the same safe.Buffer instance for stdout and stderr caused tsuru
to freeze during attach. This problem happened due to either stream
blocking indefinetely in (*safe.Buffer).ReadFrom call and preventing the
other stream from ever being read from the spdy server.
> provision/kubernetes: use separated buffers stdout and stderr attaching pods

- app/deploy.go
otherwise this field i'snt really useful as a deployment info besides being at event information
> Adding Message field to DeployData/DeployInfo.

- builder/docker/builder.go
- builder/kubernetes/builder.go
- provision/kubernetes/builder.go
- provision/kubernetes/builder_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/testing/reaction.go
- provision/provision.go
> Fix Kubernetes provisioner with authenticated registry

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/nodecontainer.go
> provision/kubernetes: add pull secrets to pod if registry auth is set

- docs/reference/api.yaml
> docs: adds app set env to swagger spec

- docs/reference/api-spec-undone.yaml
- docs/reference/api.yaml
> docs: adds volume endpoints to swagger spec

- docs/reference/api-spec-undone.yaml
- docs/reference/api.yaml
> docs/spec: adds node update/get/delete/list to swagger spec

- etc/tsuru-compose.conf
- provision/kubernetes/builder.go
- provision/kubernetes/builder_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
> use deploy-agent as sidecar for regular deploys

- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
Hello team, 
Is there any reason to Rollback being not implemented yet on Kubernetes provisioner?
Anyway, if there is none, here goes the PR.
Same process can be done with app-deploy using images however following the rollback concept is simpler.
> Adding kubernetes app-deploy-rollback support

- api/app.go
- api/app_test.go
- api/service_instance.go
- app/app.go
- service/actions.go
- service/bind_test.go
- service/service_instance.go
- service/service_instance_test.go
> api,service: allow force flag in unbind to ignore serv. endpoint errors

- docs/reference/api.yaml
> docs: add user spec to swagger

- api/pool.go
- docs/reference/api.yaml
> docs: adds pool CRUD to spec

- docs/reference/api-spec-undone.yaml
- docs/reference/api.yaml
> docs: adds spec for teams endpoints

- provision/kubernetes/cluster.go
- provision/kubernetes/cluster_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This change results in an improved performance for the app-list command
and was motivated by the analysis of a production profile with many
app-list requests happening.
Previously tsuru would make 1 query for Pods on the kubernetes API for
each App. Now a single query is made using the In operator in the
labelSelector.
Similarly each Node of each Pod would be queried with a Get() call, now
we also use the In operator on a fieldSelector.
We also reduced local MongoDB calls by calling it once per Pool instead
of once per App.
> provision/kubernetes: reduce number of kubernetes API reqs in Units() call

- api/service_instance.go
- api/service_instance_test.go
- docs/reference/api-spec-undone.yaml
- docs/reference/api.yaml
- service/actions.go
This PR adds some service instances endpoints to the spec and also changes
the updateServiceInstance to make it compatible with the formValues generated
by the hijacker from a json request.
> api,spec: service instances endpoints spec

- event/event.go
- provision/kubernetes/builder.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/servicecommon/actions.go
- provision/servicecommon/actions_test.go
- provision/servicecommon/state.go
- provision/swarm/provisioner.go
This implements cancelation for kubernetes deploys.
> provision/kubernetes: support deploy cancelation

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/swarm/docker.go
- provision/swarm/healthcheck.go
- provision/swarm/healthcheck_test.go
- provision/swarm/provisioner.go
In kubernetes it's implemented as a PostStart lifecycle hook, on swarm it uses the healthcheck cmd with some logic to ensure it only runs once after a successful execution.
Fixes #2008
> Add support for restart:after hooks in swarm and kubernetes provisioners

- docs/installing/using-tsuru-installer.rst
Hey Tsuru team,
This is my first PR with a few typos fixing.
I hope I can contribute more in the future.
> docs/installing/using-tsuru-installer: fix typos

- api/platform.go
- api/platform_test.go
- app/platform.go
- app/platform_test.go
- builder/builder.go
- builder/docker/platform.go
- builder/docker/platform_test.go
- builder/kubernetes/platform.go
- provision/kubernetes/builder.go
- provision/kubernetes/builder_test.go
- provision/kubernetes/cluster.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/kubernetes/testing/reaction.go
- provision/labels.go
- provision/provision.go
- types/app/platform.go
This PR solves #2006
depends on https://github.com/tsuru/deploy-agent/pull/13
> provision,builder: Add kubernetes platform-builder

- provision/kubernetes/cluster.go
- provision/kubernetes/cluster_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
> provision/kubernetes: ensure attach calls won't block forever

- db/storage.go
- db/storage_test.go
- storage/mongodb/cluster.go
Since PR #2078, the cluster collection name is wrong.
> Fix cluster collection

- api/apitest/setup.go
- router/api/router.go
- router/api/router_test.go
- router/galeb/client/galeb.go
- router/galeb/client/galeb_test.go
- router/galeb/client/param_types.go
- router/galeb/router.go
- router/galeb/router_test.go
- router/rebuild/rebuild.go
- router/router.go
- router/routertest/generic_suite.go
This PR also adds new generic suite tests to swap cname only.
> Fix some bugs related to swap cname only on Galeb and API routers

- api/auth.go
- api/auth_test.go
- auth/suite_test.go
- auth/team.go
- auth/team_test.go
- docs/reference/api.yaml
- storage/mongodb/team.go
- storage/storagetest/team_suite.go
- types/auth/team.go
- types/auth/team_mock.go
This PR adds support for tagging teams the same way that users can do for
apps and service instances.
Fixes #2117.
> Adds tags to Teams

- .gitignore
- docs/services/index.rst
- docs/services/open-service-broker.rst
This PR adds some initial documentation for the OSB integration.
Related to #2049.
> Adds Open Service Broker integration docs

- cmd/auth.go
- cmd/auth_test.go
- cmd/client_test.go
- cmd/cmd.go
- cmd/target.go
- cmd/target_test.go
- cmd/utils.go
- cmd/utils_test.go
Just POC with a token.d as suggested in #2088
> Creating token per target

- app/app.go
- app/app_test.go
> Add service validation when app pool changes

- api/platform.go
- api/platform_test.go
- api/server.go
- app/image/platform.go
- app/image/platform_test.go
- app/platform.go
- app/platform_test.go
- docs/reference/api.yaml
- types/app/image/platform.go
- types/app/image/platform_mock.go
- types/app/platform.go
- types/app/platform_mock.go
https://github.com/tsuru/tsuru/issues/2036
> api/platforms: add rollback endpoint

- provision/kubernetes/builder.go
- provision/kubernetes/builder_test.go
- provision/kubernetes/cluster.go
> provision/kubernetes: add clusterForPoolOrAny

- api/app.go
- api/app_test.go
- api/platform.go
- api/platform_test.go
- app/app.go
- app/app_test.go
- app/image/image.go
- app/image/image_test.go
- app/image/platform.go
- app/image/platform_test.go
- app/platform.go
- app/platform_test.go
- app/suite_test.go
- docs/reference/api.yaml
- provision/docker/docker_test.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- types/app/image/platform.go
- types/app/image/platform_mock.go
- types/app/platform_mock.go
> app,platform: app locking platform version

- api/cluster.go
- api/server.go
- docs/reference/api.yaml
> Add Cluster specification to swagger api

- app/app.go
- app/app_test.go
Apps with binded volumes can't be migrated between different provisioners.
> app: validate volumes when changing pools

- docs/reference/api.yaml
- fix URLs
- add missing `clientkey` field
- fix `pools` field type
> docs: fix cluster API spec

- docs/reference/api.yaml
Adding swagger definition for app restart service v1.0 
Issue #1992
> Change documentation for restart app method

- api/app_test.go
- app/app.go
- app/app_test.go
- provision/pool/constraint.go
- provision/pool/pool.go
- provision/pool/pool_test.go
> app,provision: allow pool constraints on plans

- app/app.go
- app/app_test.go
Related to https://github.com/tsuru/tsuru/issues/2187
> api: return platform version in app info

- api/index_templates.go
- docs/advanced_topics/metrics.rst
- docs/managing/create-platform.rst
- docs/managing/upgrading-docker.rst
- docs/using/app-deploy.rst
- docs/using/procfile.rst
Just fixing some typos I've found while reading the docs 👍
> docs: fix typos in docs

- misc/git-hooks/pre-receive
Add clean-up function to always clean tmp files on exit or err
> misc/git-hooks/pre-receive: clean-up tmp files on exit or err

- api/build.go
- api/build_test.go
To achieve full propouse of MR: tsuru/tsuru-client#113
> api/build: display "OK" message in buffer after building an image

- docs/managing/provisioners.rst
- docs/using/tsuru.yaml.rst
> docs: document Kubernetes-specific configs in tsuru.yaml

- docs/using/tsuru.yaml.rst
- provision/docker/healthcheck.go
- provision/docker/healthcheck_test.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- types/provision/provision.go
Add custom http headers support for tsuru healthcheck on tsuru.yaml
Closes #1693
> Add custom headers support for healthcheck on tsuru.yaml

- builder/docker/builder.go
- builder/docker/builder_test.go
> builder/docker: lookup tsuru.yaml file from same paths as Procfile

- app/log.go
- app/log_test.go
Emptying the bulk slice will cause the goroutine to keep consuming the
queue even in case of failures and will also prevent mongodb from
receiving a large bulk once it comes back online.
We also add a message to the log stream containing a warning of dropped
log message due to mongodb failure.
> app: drop logs in bulk slice in case of mongodb failure

- Gopkg.lock
- api/node.go
- api/node_test.go
- provision/docker/provisioner.go
- provision/docker/provisioner_test.go
- provision/docker/suite_test.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
- provision/node/node.go
- provision/provision.go
- provision/provisiontest/fake_provisioner.go
- provision/provisiontest/fake_provisioner_test.go
- provision/swarm/provisioner.go
- provision/swarm/provisioner_test.go
- types/provision/node.go
- vendor/github.com/tsuru/docker-cluster/cluster/image.go
- vendor/github.com/tsuru/docker-cluster/cluster/map_storage.go
Related to https://github.com/tsuru/tsuru/issues/1820
> Node-list filter in API 

- api/app.go
- api/app_test.go
- Fixes issue: https://github.com/tsuru/tsuru/issues/1914
> Permissions check

- .travis.yml
> enable cache to go modules

- service/endpoint.go
- service/endpoint_test.go
Previously parameters were only used with openservicebroker services, now we also send them to legacy service endpoints. This is backward compatible and won't break any existing service.
> service: Send service instance parameters to service endpoints

- api/app.go
Following the other methods pattern, it was added a line of permission in the check.
> This Pull Request is a solution for the issue 1914

- cmd/open.go
Checking if user is in WSL env and executes powershell to open GUI instead of xdg.
> feat: Adding WSL2 oauth support

- router/api/router.go
- router/router.go
- router/router_test.go
With a large number of routers listing sequentially was becoming a
problem since the request timeout for api routers is one minute.
> router: List router capabilities and info in parallel

- app/app.go
I'm experiencing an error when removing an app bound with a kubernetes-router (see some log entries below).
```
Are you sure you want to remove app "example-app"? (y/n) y
---- Removing application "example-app"...
[unbind-app-endpoint] ignored error due to force: failed to request https://kubernetes-router.example.com/api/service/backend/example-app - 500 - apps.tsuru.io "example-app" not found
... (content suppressed)
```
This occurs since we destroy the app on provisioner before unbinding from the router. In order to work around it, this PR makes the the removal of app on provisioner the last step on app removal.
> fix(app): remove app from provisioner as last step on app removal

- api/app_test.go
- api/build_test.go
- api/deploy_test.go
- api/service_instance_test.go
- api/suite_test.go
- app/app.go
- app/app_test.go
- app/image/gc/gc_test.go
- app/suite_test.go
- builder/docker/suite_test.go
- event/migrate/migrate_test.go
- provision/docker/suite_test.go
- provision/kubernetes/suite_test.go
- provision/pool/pool.go
- provision/servicecommon/actions_test.go
- router/rebuild/suite_test.go
- service/bind_test.go
- service/sync_test.go
Use first match plan as default when plan pool constraint is set
> Set default plan based on pool constraints

- etc/tsuru-local.conf
- provision/kubernetes/deploy.go
- provision/kubernetes/helpers.go
- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
This PR makes the app shell isolated container declare it's resource requirements beforehand.
The resource requirements are based from the app plan.
> Fix app shell isolated

- iaas/cloudstack/iaas.go
Change a snake case code to camelCase
> fixing the iaas.go file

- provision/kubernetes/cluster.go
- provision/kubernetes/cluster_test.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/pdb.go
- provision/kubernetes/pdb_test.go
- provision/kubernetes/provisioner.go
Change how PDB is calculated using floor(90% of HPA minReplicas) or 10% maxUnavailable
> Set PDB using 90% of HPA minReplicas or 10% maxUnavailable

- event/block.go
- event/block_test.go
Add option to check and block for extra fields (name=value) on event
> event: add check for extra event fields on event block

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
Also set user custom annotations/labels on deploy stage
> provision/kubernetes/deploy: custom annotations/labels on deploy stage

- app/actions.go
- app/app_test.go
- app/service.go
- auth/team_token.go
- auth/team_token_test.go
- auth/user.go
- types/app/app.go
- types/app/app_mock.go
- types/auth/team_token.go
- types/auth/user.go
This PR allows creating an app from a team token as required for apps managed by external tools like Terraform.
> feat(auth/token): support creating app from team token

- cmd/cmd.go
- cmd/cmd_test.go
The methods `BuildBaseManager` and `NewManager` create a `cmd.Manager` with an Exiter which uses `os.Exit()`
This makes a non-catchable exit if `cmd` is used as 3rd party library.
This PR implements a quick fix and non-breaking change consisting on adding a new method for creating a `cmd.Manager` with an Exiter which raises a `panic(*cmd.PanicExitError)` instead. 
Although this is still ugly as a 3rd party lib, it is catchable.
---
Problematic code:
```go
func main() {
defer func() {
fmt.Println("This will never get printed - sad sad :(")
}()
m := NewManager("name", "0.x", "Foo", os.Stdout, os.Stderr, os.Stdin, lookup)
m.Run(os.Args[1:])	// this will call os.Exit(0)
fmt.Println("This will never get printed - that's ok")
}
```
New code (with a …
> feat: alternative os.Exit() with panic instead

- fs/fstest/testing_fs.go
- fs/fstest/testing_fs_test.go
> fix: RecordingFs{}.Rename dirs (and its children)

- docs/using/tsuru.yaml.rst
Fixed many Grammatical issues.
Thank you!!
> Improved tsuru.yaml.rst

- provision/kubernetes/provisioner.go
- provision/kubernetes/provisioner_test.go
Fixing a bug where an app update creates an unit of base version even it wasn't running before.
Steps to reproduce:
1. App with two versions running simultaneously;
1.1. Base version w/ zero units (`tsuru unit remove ... <all units>`);
1.2. Extra version running regardless the numbers of units; 
2.  Run an app update (allowing restart);
3. A new units of base version gets running;
> fix(k8s): app update should not create unit of zeroed process

- CONTRIBUTORS
- README.md
Just found a small typo in the README and fixed it.
> Small typo in README.md

- provision/kubernetes/cluster.go
- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/helpers.go
- provision/kubernetes/helpers_test.go
Add new cluster option "topology-spread-constraints" to specify topology constraints
> provision/kubernetes: add topologySpreadConstraint support

- provision/kubernetes/deploy.go
- provision/kubernetes/deploy_test.go
- provision/kubernetes/job.go
- provision/kubernetes/job_test.go
- provision/kubernetes/well_known.go
Also: DestroyJob now deletes the job's SA
> feat: Enable Service Account Job Annotations

- provision/provision.go
- provision/provision_test.go
also changes test comparison from regex to pure string
> feat: validation for prometheus trigger name

- Makefile
- auth/oidc/oidc_test.go
- job/suite_test.go
There is also a fix for a **oidc_test** where a new user is inserted in the main collection as well.
> fix: preserve main collection when running make test

- docs/reference/api.yaml
feat: add auto scale down behavior to client
> feat: scaling behavior settings in API definition

- app/actions.go
- app/app_test.go
this is a fix of MR https://github.com/tsuru/tsuru/pull/2747
> fix: cert issuer constraints with blacklist

- api/app.go
- api/auth.go
- api/deploy.go
- api/job.go
- api/permission.go
- api/volume.go
- api/webhook.go
evt.Done need to catch error to attach on a tsuru event
> Audit missing errors
